# Generated by Django 5.2.10 on 2026-07-20 16:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0035_employee_notify_court_events_telegram'),
        ('files', '0004_storedfile_bubble_id'),
        ('procedure', '0022_request_pages_count_and_ops_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='KommersantMessageType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('applicable_kinds', models.JSONField(blank=True, default=list, help_text='Список из restructuring/realization. Пусто — показывать всегда.', verbose_name='Виды процедур')),
                ('blank_checkbox', models.CharField(blank=True, choices=[('restructuring', 'О введении реструктуризации долгов'), ('realization', 'О введении реализации имущества'), ('', 'Не отмечать')], max_length=32, verbose_name='Чекбокс в бланке заявки')),
                ('text_template', models.TextField(blank=True, help_text='Плейсхолдеры вида {ФИО должника} — см. подсказку в справочнике.', verbose_name='Шаблон текста сообщения')),
                ('order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_draft', models.BooleanField(default=True, help_text='Снимите, когда формулировку подтвердил арбитражный управляющий.', verbose_name='Черновик (не согласован с АУ)')),
            ],
            options={
                'verbose_name': 'Тип сообщения (Коммерсантъ)',
                'verbose_name_plural': 'Типы сообщений (Коммерсантъ)',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KommersantPublication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('generated', 'Текст сформирован'), ('sent', 'Заявка отправлена'), ('invoiced', 'Счёт получен'), ('paid', 'Оплачено'), ('published', 'Опубликовано'), ('cancelled', 'Отменено')], db_index=True, default='draft', max_length=16, verbose_name='Статус')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Текст сообщения')),
                ('overrides', models.JSONField(blank=True, default=dict, help_text='Поля, введённые вручную поверх данных CRM.', verbose_name='Ручные правки полей')),
                ('accounting_docs_to', models.CharField(choices=[('manager', 'На арбитражного управляющего'), ('debtor', 'На должника')], default='manager', max_length=16, verbose_name='Отчётные документы оформить на')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Текст сформирован')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Заявка отправлена')),
                ('sent_to', models.CharField(blank=True, max_length=255, verbose_name='Куда отправлено')),
                ('sent_from', models.CharField(blank=True, max_length=255, verbose_name='С какого адреса')),
                ('sent_message_id', models.CharField(blank=True, db_index=True, help_text='По нему ловим ответ ИД со счётом (In-Reply-To/References).', max_length=255, verbose_name='Message-ID письма')),
                ('send_error', models.TextField(blank=True, verbose_name='Ошибка отправки')),
                ('invoice_received_at', models.DateTimeField(blank=True, null=True, verbose_name='Счёт получен')),
                ('invoice_number', models.CharField(blank=True, max_length=64, verbose_name='Номер счёта')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Дата счёта')),
                ('invoice_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма счёта, ₽')),
                ('invoice_message_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Message-ID письма со счётом')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Счёт оплачен')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Дата публикации')),
                ('newspaper_number', models.CharField(blank=True, max_length=64, verbose_name='Номер газеты')),
                ('announcement_number', models.CharField(blank=True, max_length=64, verbose_name='Номер объявления')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('blank_docx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='files.storedfile', verbose_name='Заявка .docx')),
                ('blank_pdf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='files.storedfile', verbose_name='Заявка .pdf (с подписью)')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kommersant_publications', to='procedure.bankruptcycase', verbose_name='Дело')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.employee', verbose_name='Кто создал')),
                ('invoice_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='files.storedfile', verbose_name='Файл счёта')),
                ('message_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='kommersant.kommersantmessagetype', verbose_name='Тип сообщения')),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kommersant_publications', to='procedure.procedure', verbose_name='Процедура')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.employee', verbose_name='Кто отправил')),
            ],
            options={
                'verbose_name': 'Публикация в «Коммерсантъ»',
                'verbose_name_plural': 'Публикации в «Коммерсантъ»',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KommersantAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('court_act', 'Судебный акт о введении процедуры'), ('authority', 'Акт о полномочиях управляющего'), ('other', 'Иной документ')], default='other', max_length=32, verbose_name='Вид документа')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('stored_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='files.storedfile', verbose_name='Файл')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='kommersant.kommersantpublication', verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Вложение к заявке',
                'verbose_name_plural': 'Вложения к заявке',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='kommersantpublication',
            index=models.Index(fields=['case', 'status'], name='kommersant__case_id_bd0f5f_idx'),
        ),
    ]
