# Generated by Django 5.2.10 on 2026-05-18 09:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_seed_menu_legal_entities'),
        ('crm', '0051_remove_client_crm_client_is_iden_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_date', models.DateField(verbose_name='Дата платежа по графику')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование платежа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма начисления')),
                ('status', models.CharField(choices=[('scheduled', 'В графике'), ('overdue', 'Просрочен'), ('paid', 'Оплачен')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='crm.client', verbose_name='Клиент')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_charges', to='core.employee', verbose_name='Кто внёс сведения')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='crm.service', verbose_name='Услуга')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_charges', to='core.employee', verbose_name='Кто отредактировал')),
            ],
            options={
                'verbose_name': 'Начисление',
                'verbose_name_plural': 'Начисления',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_types', to='crm.servicename', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Тип расхода',
                'verbose_name_plural': 'Типы расходов',
                'ordering': ['service_name__short_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IncomeType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_types', to='crm.servicename', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Тип дохода',
                'verbose_name_plural': 'Типы доходов',
                'ordering': ['service_name__short_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IncomingAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('cash', 'Касса'), ('bank', 'Банк')], max_length=10, verbose_name='Тип')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Счёт прихода',
                'verbose_name_plural': 'Счета прихода',
                'ordering': ['account_type', 'name'],
                'constraints': [models.UniqueConstraint(fields=('account_type', 'name'), name='unique_incoming_account')],
            },
        ),
        migrations.CreateModel(
            name='OutgoingAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('cash', 'Касса'), ('bank', 'Банк')], max_length=10, verbose_name='Тип')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Счёт расхода',
                'verbose_name_plural': 'Счета расхода',
                'ordering': ['account_type', 'name'],
                'constraints': [models.UniqueConstraint(fields=('account_type', 'name'), name='unique_outgoing_account')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_date', models.DateField(verbose_name='Дата платежа')),
                ('direction', models.CharField(choices=[('in', 'Входящий'), ('out', 'Исходящий')], max_length=10, verbose_name='Тип платежа')),
                ('amount_in', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Сумма входящего')),
                ('amount_out', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Сумма исходящего')),
                ('payment_form', models.CharField(choices=[('cash', 'Наличный'), ('cashless', 'Безналичный')], max_length=10, verbose_name='Форма оплаты')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.charge', verbose_name='Платёж по графику')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crm.client', verbose_name='Клиент')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to='core.employee', verbose_name='Кто внёс сведения')),
                ('expense_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.expensetype', verbose_name='Тип расхода')),
                ('income_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.incometype', verbose_name='Тип дохода')),
                ('incoming_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.incomingaccount', verbose_name='Куда поступил')),
                ('outgoing_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.outgoingaccount', verbose_name='Откуда оплачено')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='crm.service', verbose_name='Услуга')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_payments', to='core.employee', verbose_name='Кто отредактировал')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='expensetype',
            constraint=models.UniqueConstraint(fields=('service_name', 'name'), name='unique_expense_type_per_service'),
        ),
        migrations.AddConstraint(
            model_name='incometype',
            constraint=models.UniqueConstraint(fields=('service_name', 'name'), name='unique_income_type_per_service'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['client', '-payment_date'], name='finance_pay_client__97bad6_idx'),
        ),
    ]
