# Generated by Django 5.2.10 on 2026-05-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_seed_bfl_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='bubble_id',
            field=models.CharField(blank=True, help_text='ID записи Money (accrual) в исходной CRM на bubble.io', max_length=64, null=True, unique=True, verbose_name='Bubble ID'),
        ),
        migrations.AddField(
            model_name='payment',
            name='bubble_id',
            field=models.CharField(blank=True, help_text='ID записи Money (debit/credit) в исходной CRM на bubble.io', max_length=64, null=True, unique=True, verbose_name='Bubble ID'),
        ),
    ]
