# Generated by Django 5.2.10 on 2026-08-27 11:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0040_employee_can_access_callcenter'),
        ('crm', '0102_alter_correspondence_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallCenterColumn',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, help_text='Короткое пояснение оператору — показывается в шапке колонки.', max_length=255, verbose_name='Подсказка')),
                ('color', models.CharField(choices=[('neutral', 'Серый'), ('primary', 'Основной'), ('info', 'Синий'), ('success', 'Зелёный'), ('warning', 'Жёлтый'), ('error', 'Красный')], default='neutral', max_length=16, verbose_name='Цвет')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_default', models.BooleanField(default=False, help_text='Сюда попадают карточки, добавленные на доску. Такая колонка одна — при включении флаг снимается с прежней.', verbose_name='Колонка по умолчанию')),
                ('wip_limit', models.PositiveIntegerField(default=0, help_text='0 — без лимита. При превышении счётчик колонки краснеет (мягкое ограничение, перетаскивать не мешает).', verbose_name='Лимит карточек')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Колонка колл-центра',
                'verbose_name_plural': 'Колонки колл-центра',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CallCenterCard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('moved_at', models.DateTimeField(auto_now_add=True, verbose_name='Перемещена')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='callcenter_card', to='crm.client', verbose_name='Клиент')),
                ('moved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callcenter_moves', to='core.employee', verbose_name='Кто переместил')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='callcenter.callcentercolumn', verbose_name='Колонка')),
            ],
            options={
                'verbose_name': 'Карточка колл-центра',
                'verbose_name_plural': 'Карточки колл-центра',
                'ordering': ['-moved_at'],
                'indexes': [models.Index(fields=['column', '-moved_at'], name='callcenter__column__d8e10c_idx')],
            },
        ),
    ]
