# Generated by Django 5.2.10 on 2026-08-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0002_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='callcentercard',
            name='source',
            field=models.CharField(choices=[('manual', 'Вручную'), ('call', 'Входящий звонок'), ('tg_lead', 'Лид из Telegram')], default='manual', help_text='Откуда карточка попала на доску — видно оператору значком.', max_length=16, verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='callcentercolumn',
            name='catch_telegram_leads',
            field=models.BooleanField(default=False, help_text='Заявка с лендинга, пришедшая в канал лидов, попадает карточкой в эту колонку. Колонка-приёмник одна.', verbose_name='Ловит лиды из Telegram-канала'),
        ),
        migrations.AddField(
            model_name='callcentercolumn',
            name='catch_unknown_calls',
            field=models.BooleanField(default=False, help_text='Входящий с номера, которого нет в базе: заводится неидентифицированный клиент и его карточка встаёт в эту колонку. Колонка-приёмник одна.', verbose_name='Ловит входящие звонки с неизвестных номеров'),
        ),
    ]
