# Generated by Django 5.2.10 on 2026-08-27 13:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0004_seed_intake'),
        ('core', '0040_employee_can_access_callcenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedPhone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(help_text='Хранится нормализованным: 79001234567.', max_length=32, unique=True, verbose_name='Номер')),
                ('comment', models.CharField(blank=True, help_text='Зачем заблокирован — «робот-обзвон», «реклама», «ошиблись номером».', max_length=255, verbose_name='Причина')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='Срабатываний')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний звонок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_phones', to='core.employee', verbose_name='Кто добавил')),
            ],
            options={
                'verbose_name': 'Номер в чёрном списке',
                'verbose_name_plural': 'Чёрный список номеров',
                'ordering': ['-last_seen_at', '-created_at'],
            },
        ),
    ]
