# Generated by Django 5.2.10 on 2026-08-27 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0005_blockedphone'),
        ('core', '0040_employee_can_access_callcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='callcentercard',
            name='next_action',
            field=models.CharField(blank=True, help_text='Что сделать: «Позвонить», «Отправить договор», …', max_length=255, verbose_name='Следующее действие'),
        ),
        migrations.AddField(
            model_name='callcentercard',
            name='next_action_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Запланированные дата и время. Индекс нужен будущей напоминалке: она выбирает наступившие по времени.', null=True, verbose_name='Когда'),
        ),
        migrations.AddField(
            model_name='callcentercard',
            name='next_action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callcenter_planned_actions', to='core.employee', verbose_name='Кто запланировал'),
        ),
    ]
