# Generated by Django 5.2.10 on 2026-08-27 14:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0006_callcentercard_next_action_and_more'),
        ('core', '0040_employee_can_access_callcenter'),
        ('crm', '0102_alter_correspondence_comments'),
        ('telephony', '0008_link_call_groups_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('hint', models.CharField(blank=True, help_text='Когда выбирать этот результат — показывается оператору.', max_length=255, verbose_name='Подсказка')),
                ('color', models.CharField(choices=[('neutral', 'Серый'), ('primary', 'Основной'), ('info', 'Синий'), ('success', 'Зелёный'), ('warning', 'Жёлтый'), ('error', 'Красный')], default='neutral', max_length=16, verbose_name='Цвет')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('suggest_next_action', models.BooleanField(default=False, verbose_name='Предлагать запланировать действие')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Результат звонка',
                'verbose_name_plural': 'Результаты звонков',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CallOutcome',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_key', models.CharField(help_text='Uniqueid ноги + внутренний номер — как у карточки «вам звонили». Идемпотентность: повторное событие не плодит вторую модалку.', max_length=80, unique=True, verbose_name='Ключ ноги звонка')),
                ('direction', models.CharField(choices=[('in', 'Входящий'), ('out', 'Исходящий')], max_length=4, verbose_name='Направление')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Номер собеседника')),
                ('answered', models.BooleanField(default=False, verbose_name='Разговор состоялся')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Когда звонили')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('filled_at', models.DateTimeField(blank=True, null=True, verbose_name='Заполнен')),
                ('postponed_at', models.DateTimeField(blank=True, null=True, verbose_name='Отложен')),
                ('call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callcenter_outcomes', to='telephony.call', verbose_name='Звонок в журнале')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_outcomes', to='crm.client', verbose_name='Клиент')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_outcomes', to='core.employee', verbose_name='Сотрудник')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outcomes', to='callcenter.callresult', verbose_name='Результат')),
            ],
            options={
                'verbose_name': 'Результат состоявшегося звонка',
                'verbose_name_plural': 'Результаты состоявшихся звонков',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['employee', 'filled_at'], name='callcenter__employe_29276c_idx')],
            },
        ),
    ]
