# Generated by Django 5.2.10 on 2026-08-27 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0008_seed_results'),
        ('core', '0040_employee_can_access_callcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='callcentercard',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callcenter_cards', to='core.employee', verbose_name='Оператор'),
        ),
        migrations.AddField(
            model_name='callcentercard',
            name='taken_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Взята в работу'),
        ),
    ]
