# Generated by Django 5.2.10 on 2026-05-10 14:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevopsAgentJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=20)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('running', 'Выполняется'), ('done', 'Готово'), ('failed', 'Ошибка')], default='queued', max_length=20)),
                ('output', models.TextField(blank=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Agent job',
                'verbose_name_plural': 'Agent jobs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='Например: prod', unique=True, verbose_name='Имя')),
                ('base_url', models.URLField(help_text='https://siricrm.ru', verbose_name='Base URL')),
                ('agent_token_env', models.CharField(default='DEVOPS_AGENT_TOKEN_PROD', help_text='Переменная окружения с Bearer-токеном агента', max_length=100, verbose_name='Имя env-переменной с токеном')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Окружение',
                'verbose_name_plural': 'Окружения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DevopsAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('status', 'Статус'), ('backup', 'Бэкап БД'), ('pull_db', 'Pull prod → dev'), ('deploy', 'Деплой')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('running', 'Выполняется'), ('done', 'Готово'), ('failed', 'Ошибка')], default='queued', max_length=20)),
                ('remote_job_id', models.CharField(blank=True, help_text='UUID job на прод-агенте', max_length=64)),
                ('output', models.TextField(blank=True)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='devops.environment')),
            ],
            options={
                'verbose_name': 'DevOps action',
                'verbose_name_plural': 'DevOps actions',
                'ordering': ['-started_at'],
            },
        ),
    ]
