# Generated by Django 5.2.10 on 2026-05-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devopsaction',
            name='action_type',
            field=models.CharField(choices=[('status', 'Статус'), ('backup', 'Бэкап БД'), ('list_backups', 'Список бэкапов'), ('pull_db', 'Pull prod → dev'), ('deploy', 'Деплой')], max_length=20),
        ),
    ]
