# Generated by Django 5.2.10 on 2026-05-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0002_alter_devopsaction_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devopsaction',
            name='action_type',
            field=models.CharField(choices=[('status', 'Статус'), ('backup', 'Бэкап БД'), ('list_backups', 'Список бэкапов'), ('pull_db', 'Pull prod → dev'), ('deploy', 'Деплой'), ('rebuild', 'Rebuild образов')], max_length=20),
        ),
    ]
