# Generated by Django 5.2.10 on 2026-05-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0005_rename_self_env_to_dev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devopsaction',
            name='action_type',
            field=models.CharField(choices=[('status', 'Статус'), ('backup', 'Бэкап БД'), ('list_backups', 'Список бэкапов'), ('s3_stats', 'S3: статистика'), ('pull_db', 'Скопировать БД сюда (prod → dev)'), ('push_db', 'Залить эту БД в цель (dev → prod)'), ('deploy', 'Деплой'), ('git_log', 'Версии (git log)'), ('rollback', 'Откат версии'), ('rebuild', 'Rebuild образов')], max_length=20),
        ),
    ]
