# Generated by Django 5.2.10 on 2026-05-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0007_alter_devopsaction_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devopsaction',
            name='action_type',
            field=models.CharField(choices=[('status', 'Статус'), ('backup', 'Бэкап БД'), ('list_backups', 'Список бэкапов'), ('s3_stats', 'S3: статистика'), ('disk_usage', 'Диск: разбивка использования'), ('pull_db', 'Скопировать БД сюда (prod → dev)'), ('push_db', 'Залить эту БД в цель (dev → prod)'), ('dumpdata_tables', 'Выгрузить выбранные таблицы (dumpdata)'), ('loaddata_tables', 'Загрузить выбранные таблицы (loaddata UPSERT)'), ('pull_tables', 'Затянуть выбранные таблицы сюда (prod → dev)'), ('push_tables', 'Залить выбранные таблицы в цель (dev → prod)'), ('deploy', 'Деплой'), ('git_log', 'Версии (git log)'), ('rollback', 'Откат версии'), ('rebuild', 'Rebuild образов')], max_length=20),
        ),
    ]
