# Generated by Django 5.2.10 on 2026-02-08 15:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0006_message_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название отдела')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель отдела')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('operator', 'Оператор'), ('manager', 'Менеджер'), ('consultant', 'Консультант'), ('assitent_legal', 'Помощник юриста'), ('lawyer', 'Юрист'), ('head_dep', 'Руководитель отдела'), ('arbitration', 'Арбитражный управляющий'), ('agent', 'Агент'), ('managing_partner', 'Управляющий партнер'), ('admin', 'Администратор')], default='operator', max_length=20, verbose_name='Роль')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_online', models.BooleanField(default=False, verbose_name='Онлайн')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата присоединения')),
                ('dismiss_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.department', verbose_name='Отдел')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='EmployeeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'Вход'), ('logout', 'Выход'), ('message_sent', 'Сообщение отправлено'), ('message_received', 'Сообщение получено'), ('client_add', 'Клиент добавлен'), ('client_assigned', 'Клиент назначен'), ('client_edit', 'Данные Клиента изменены'), ('client_reassigned', 'Клиент переназначен'), ('client_status_changed', 'Статус клиента изменен'), ('note_added', 'Заметка добавлена'), ('client_unassigned', 'Клиент разъединен')], max_length=50, verbose_name='Действие')),
                ('description', models.TextField(verbose_name='Описание')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_logs', to='crm.client', verbose_name='Клиент')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.employee', verbose_name='Сотрудник')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='crm.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Лог сотрудника',
                'verbose_name_plural': 'Логи осотрудников',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['employee', 'timestamp'], name='core_employ_employe_a3076b_idx'), models.Index(fields=['action', 'timestamp'], name='core_employ_action_007d62_idx'), models.Index(fields=['client', 'timestamp'], name='core_employ_client__1299df_idx')],
            },
        ),
    ]
