# Generated by Django 5.2.10 on 2026-04-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employee_patronymic'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone_internal',
            field=models.CharField(blank=True, max_length=10, verbose_name='Внутренний номер'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_mobile',
            field=models.CharField(blank=True, max_length=20, verbose_name='Мобильный телефон'),
        ),
    ]
