# Generated by Django 5.2.10 on 2026-04-15 08:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employee_phones'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Конфигурация дашборда',
                'verbose_name_plural': 'Конфигурации дашбордов',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('icon', models.CharField(blank=True, max_length=10, verbose_name='Иконка')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('section', models.CharField(blank=True, max_length=100, verbose_name='Секция меню')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('use_htmx', models.BooleanField(default=True, verbose_name='Загрузка через HTMX')),
                ('requires_superuser', models.BooleanField(default=False, verbose_name='Только для суперпользователя')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Идентификатор')),
                ('widget_type', models.CharField(choices=[('stats', 'Статистика'), ('chart', 'График'), ('table', 'Таблица'), ('list', 'Список'), ('custom', 'Кастомный')], default='custom', max_length=20, verbose_name='Тип')),
                ('template_name', models.CharField(blank=True, max_length=255, verbose_name='Шаблон')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Виджет',
                'verbose_name_plural': 'Виджеты',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='has_messenger_access',
            field=models.BooleanField(default=True, verbose_name='Доступ к мессенджеру'),
        ),
        migrations.AddField(
            model_name='employee',
            name='dashboard_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.dashboardconfig', verbose_name='Конфигурация дашборда'),
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='menu_items',
            field=models.ManyToManyField(blank=True, to='core.menuitem', verbose_name='Пункты меню'),
        ),
        migrations.AddField(
            model_name='dashboardconfig',
            name='widgets',
            field=models.ManyToManyField(blank=True, to='core.widget', verbose_name='Виджеты'),
        ),
    ]
