# Generated by Django 5.2.10 on 2026-04-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_references_icon_emoji'),
        ('crm', '0038_paymentprocedure_servicecommonstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='services_allowed',
            field=models.ManyToManyField(blank=True, related_name='allowed_employees', to='crm.servicename', verbose_name='Доступные услуги'),
        ),
    ]
