# Generated by Django 5.2.10 on 2026-05-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_seed_menu_legal_entities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('operator', 'Оператор'), ('manager', 'Менеджер'), ('consultant', 'Консультант'), ('assitent_legal', 'Помощник юриста'), ('lawyer', 'Юрист'), ('head_dep', 'Руководитель отдела'), ('arbitration', 'Арбитражный управляющий'), ('agent', 'Агент'), ('managing_partner', 'Управляющий партнер'), ('accountant', 'Бухгалтер'), ('admin', 'Администратор')], default='operator', max_length=20, verbose_name='Роль'),
        ),
    ]
