# Generated by Django 5.2.10 on 2026-05-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bubble_id',
            field=models.CharField(blank=True, help_text='ID записи User в исходной CRM на bubble.io', max_length=64, null=True, unique=True, verbose_name='Bubble ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('operator', 'Оператор'), ('manager', 'Менеджер'), ('consultant', 'Консультант'), ('assitent_legal', 'Помощник юриста'), ('lawyer', 'Юрист'), ('head_dep', 'Руководитель отдела'), ('arbitration', 'Арбитражный управляющий'), ('arbitr_assistant', 'Помощник АУ'), ('agent', 'Агент'), ('managing_partner', 'Управляющий партнер'), ('accountant', 'Бухгалтер'), ('admin', 'Администратор')], default='operator', max_length=20, verbose_name='Роль'),
        ),
    ]
