# Generated by Django 5.2.10 on 2026-05-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_employee_bubble_id_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='accept_telegram_leads',
            field=models.BooleanField(default=False, help_text='Заявки с лендингов через @Sirius_system_bot будут попадать в «Мой канбан» в колонку «Лиды из Telegram».', verbose_name='Принимать лиды из Telegram'),
        ),
    ]
