# Generated by Django 5.2.10 on 2026-05-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_employee_accept_telegram_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='sees_all_clients',
            field=models.BooleanField(default=False, help_text='Сотрудники этого отдела видят всех клиентов компании (например, отдел продаж, который сопровождает клиента от первого обращения до архива).', verbose_name='Видит всех клиентов'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_owner',
            field=models.BooleanField(default=False, help_text='Видит ВСЁ (включая Django-admin). Только для основателя/админа.', verbose_name='Owner (root)'),
        ),
    ]
