# Generated by Django 5.2.10 on 2026-05-31 18:46

from django.db import migrations, models


# Отделы, которым по умолчанию даём право редактировать график платежей:
# коммерческий отдел (продажи) + бухгалтерия. Можно менять галкой в карточке
# отдела (Department.can_edit_payment_schedule).
_SEED_DEPARTMENTS = ["Отдел продаж БФЛ", "Бухгалтерия"]


def seed(apps, schema_editor):
    Department = apps.get_model("core", "Department")
    n = Department.objects.filter(name__in=_SEED_DEPARTMENTS).update(
        can_edit_payment_schedule=True,
    )
    print(f"  can_edit_payment_schedule=True у {n} отдел(ов)")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_arbitr_menu_attach_to_configs'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='can_edit_payment_schedule',
            field=models.BooleanField(default=False, help_text='Сотрудники этого отдела могут составлять/редактировать график платежей и начисления (например, коммерческий отдел и бухгалтерия). Просмотр графика доступен всем.', verbose_name='Редактирует график платежей'),
        ),
        migrations.RunPython(seed, noop),
    ]
