# Generated by Django 5.2.10 on 2026-06-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_department_can_edit_payment_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_handle_scans',
            field=models.BooleanField(default=False, help_text='Доступ к лотку «Входящие сканы»: видеть присланные со сканера документы и привязывать их к клиентам.', verbose_name='Обработка входящих сканов'),
        ),
    ]
