# Generated by Django 5.2.10 on 2026-06-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_employee_can_handle_scans'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='scanner_name',
            field=models.CharField(blank=True, default='', help_text='Метка устройства (device) из scan-agent. Сканы с этой меткой по умолчанию показываются этому сотруднику в лотке «Входящие сканы». Можно задать один и тот же сканер нескольким сотрудникам.', max_length=100, verbose_name='Имя сканера'),
        ),
    ]
