# Generated by Django 5.2.10 on 2026-06-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_employee_scanner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_merge_clients',
            field=models.BooleanField(default=False, help_text='Доступ к кнопке «Объединить» в карточке клиента — самостоятельное слияние карточек-дублей.', verbose_name='Объединение клиентов'),
        ),
    ]
