# Generated by Django 5.2.10 on 2026-06-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_set_can_merge_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, help_text='Привязывается через бота уведомлений по одноразовому коду из профиля. Нужен для дублирования уведомлений в Telegram.', null=True, unique=True, verbose_name='Telegram chat_id (уведомления)'),
        ),
    ]
