# Generated by Django 5.2.10 on 2026-06-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_employee_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_docs_collection',
            field=models.BooleanField(default=False, help_text='Отметьте на отделе сбора документов. При передаче услуги в этот отдел в услугу проставляется «Дата передачи в отдел сбора документов» (используется в карточке процедуры).', verbose_name='Отдел сбора документов'),
        ),
    ]
