# Generated by Django 5.2.10 on 2026-07-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_fix_daily_report_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_edit_finance',
            field=models.BooleanField(default=False, help_text='Право создавать и изменять платежи (входящие/исходящие). Точечный флаг — обычно даётся бухгалтерии; можно выдать руководству (managing_partner) без изменения роли.', verbose_name='Редактирование финансов'),
        ),
    ]
