# Generated by Django 5.2.10 on 2026-07-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_grant_finance_to_kanygina'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_view_all_clients',
            field=models.BooleanField(default=False, help_text='Точечный доступ ко всей клиентской базе без смены роли. Даётся сотрудникам, чьи роли не входят в MANAGEMENT_ROLES (admin/head_dep/managing_partner), но которым нужен общий обзор (например, arbitration-АУ, помогающий с общей загрузкой).', verbose_name='Видит всех клиентов'),
        ),
    ]
