# Generated by Django 5.2.10 on 2026-07-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_grant_view_all_to_kanygina'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='avatar_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='Аватар (ключ в S3)'),
        ),
    ]
