# Generated by Django 5.2.10 on 2026-07-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_employee_avatar_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='efrsb_login',
            field=models.CharField(blank=True, max_length=255, verbose_name='Логин ЕФРСБ'),
        ),
        migrations.AddField(
            model_name='employee',
            name='efrsb_password_enc',
            field=models.CharField(blank=True, max_length=512, verbose_name='Пароль ЕФРСБ (шифр.)'),
        ),
    ]
