# Generated by Django 5.2.10 on 2026-07-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_employee_efrsb_login_employee_efrsb_password_enc'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='notify_court_events_max',
            field=models.BooleanField(default=False, verbose_name='Уведомлять в MAX о судебных событиях'),
        ),
    ]
