# Generated by Django 5.2.10 on 2026-07-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_employee_notify_court_events_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='kommersant_email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='E-mail для «Коммерсанта»'),
        ),
        migrations.AddField(
            model_name='employee',
            name='kommersant_password_enc',
            field=models.CharField(blank=True, max_length=512, verbose_name='Пароль почты «Коммерсанта» (шифр.)'),
        ),
    ]
