# Generated by Django 5.2.10 on 2026-08-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_employee_kommersant_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_listen_calls',
            field=models.BooleanField(default=False, help_text='Право слушать записи телефонных разговоров в разделе «Звонки». Каждое прослушивание протоколируется.', verbose_name='Доступ к записям разговоров'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sip_extension',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Трёхзначный номер сотрудника на Asterisk (201, 301, 502…). По нему звонки привязываются к сотруднику, работает звонок по клику и всплывашка при входящем.', max_length=8, verbose_name='Внутренний номер АТС'),
        ),
    ]
