# Generated by Django 5.2.10 on 2026-08-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_employee_can_listen_calls_employee_sip_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='can_listen_calls',
            field=models.BooleanField(default=False, help_text='Свои записи (со своего внутреннего номера) слушает каждый сотрудник, отдельного права не нужно. Этот флаг открывает записи ВСЕХ сотрудников — руководству он и так доступен, флаг нужен для остальных (например, контроля качества). Каждое прослушивание протоколируется.', verbose_name='Доступ к ЧУЖИМ записям разговоров'),
        ),
    ]
