# Generated by Django 5.2.10 on 2026-08-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_employee_can_listen_calls'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='notify_missed_calls',
            field=models.BooleanField(default=True, help_text='Личные сообщения в Telegram и MAX о пропущенных входящих той группы, к которой относится сотрудник. Реестр «Пропущенные» в разделе «Звонки» флаг не затрагивает.', verbose_name='Уведомлять о пропущенных звонках'),
        ),
    ]
