# Generated by Django 5.2.10 on 2026-08-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_employee_notify_missed_calls'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_access_callcenter',
            field=models.BooleanField(default=False, help_text='Доступ к доске колл-центра (раздел «Колл-центр»). Гейт точечным флагом, а не ролью: роль operator — значение по умолчанию у всех, кому её не меняли.', verbose_name='Рабочее место колл-центра'),
        ),
    ]
