# Generated by Django 5.2.10 on 2026-06-13 20:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_seed_menu'),
        ('core', '0022_set_can_merge_clients'),
        ('crm', '0082_message_message_template_message_template_params_and_more'),
        ('finance', '0003_charge_bubble_id_payment_bubble_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourcePoll',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('statement', 'Выписка р/с'), ('acquiring', 'Эквайринг')], db_index=True, max_length=16, verbose_name='Источник')),
                ('found', models.PositiveIntegerField(default=0, verbose_name='Найдено входящих')),
                ('created', models.PositiveIntegerField(default=0, verbose_name='Новых')),
                ('ok', models.BooleanField(default=True, verbose_name='Успех')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка')),
            ],
            options={
                'verbose_name': 'Опрос источника',
                'verbose_name_plural': 'Опросы источников',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncomingPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('statement', 'Выписка р/с'), ('acquiring', 'Эквайринг')], max_length=16, verbose_name='Источник')),
                ('external_id', models.CharField(max_length=128, verbose_name='ID операции в источнике')),
                ('occurred_at', models.DateTimeField(verbose_name='Дата/время платежа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('payer_name', models.CharField(blank=True, max_length=255, verbose_name='Плательщик / ФИО')),
                ('payer_inn', models.CharField(blank=True, max_length=16, verbose_name='ИНН плательщика')),
                ('payer_phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон (введён клиентом)')),
                ('purpose', models.TextField(blank=True, verbose_name='Назначение')),
                ('order_id', models.CharField(blank=True, max_length=128, verbose_name='OrderId эквайринга')),
                ('status', models.CharField(choices=[('new', 'Не привязан'), ('bound', 'Привязан'), ('unidentified', 'Неопознанный')], db_index=True, default='new', max_length=16, verbose_name='Статус')),
                ('note', models.TextField(blank=True, verbose_name='Комментарий бухгалтера')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='Сырой ответ источника')),
                ('bound_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда привязан')),
                ('bound_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bound_incoming_payments', to='core.employee', verbose_name='Кто привязал')),
                ('bound_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_payments', to='crm.client', verbose_name='Клиент')),
                ('created_payments', models.ManyToManyField(blank=True, related_name='+', to='finance.payment', verbose_name='Созданные платежи')),
            ],
            options={
                'verbose_name': 'Входящий платёж',
                'verbose_name_plural': 'Входящие платежи',
                'ordering': ['-occurred_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'source'], name='accounting__status_5f05a0_idx'), models.Index(fields=['-occurred_at'], name='accounting__occurre_d04c38_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_incoming_payment_per_source')],
            },
        ),
    ]
