# Generated by Django 5.2.10 on 2026-06-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_seed_acquiring_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingpayment',
            name='is_settlement',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Эквайринг-зачисление'),
        ),
    ]
