# Generated by Django 5.2.10 on 2026-06-14 00:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_backfill_is_settlement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquiringPrepay',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='OrderId')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='ФИО (введено клиентом)')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон (введён клиентом)')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Сумма')),
                ('matched', models.BooleanField(default=False, verbose_name='Сопоставлен с платежом')),
            ],
            options={
                'verbose_name': 'Pre-pay эквайринга',
                'verbose_name_plural': 'Pre-pay эквайринга',
                'ordering': ['-created_at'],
            },
        ),
    ]
