# Generated by Django 5.2.10 on 2026-07-17 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0034_employee_max_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Часть URL: /wiki/a/<slug>/. Заполнится сама из заголовка.', max_length=140, unique=True, verbose_name='Адрес (slug)')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('order', models.PositiveIntegerField(default=0, help_text='Внутри своего уровня, по возрастанию.', verbose_name='Порядок')),
                ('body', models.TextField(blank=True, verbose_name='Текст (markdown)')),
                ('is_published', models.BooleanField(default=True, help_text='Снятая с публикации статья видна только редакторам руководства.', verbose_name='Опубликована')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='wiki.wikiarticle', verbose_name='Родительский раздел')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.employee', verbose_name='Кто правил последним')),
            ],
            options={
                'verbose_name': 'Статья руководства',
                'verbose_name_plural': 'Статьи руководства',
                'ordering': ['order', 'title'],
                'indexes': [models.Index(fields=['parent', 'order'], name='wiki_wikiar_parent__c8a372_idx')],
            },
        ),
    ]
