# Generated by Django 5.2.10 on 2026-05-02 21:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_seed_menu_legal_entities'),
        ('crm', '0046_servicecommonstatus_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('color', models.CharField(default='badge-neutral', help_text='badge-success, badge-error, badge-warning, badge-info и т.д.', max_length=40, verbose_name='Цвет (daisyUI badge)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Итог консультации',
                'verbose_name_plural': 'Итоги консультаций',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_start', models.DateTimeField(verbose_name='Начало')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Длительность (мин)')),
                ('status', models.CharField(choices=[('free', 'Свободно'), ('booked', 'Записан'), ('done', 'Проведена'), ('cancelled', 'Отменена')], default='free', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий оператора')),
                ('consultant_notes', models.TextField(blank=True, verbose_name='Заметки консультанта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_booked', to='core.employee', verbose_name='Записал')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='crm.client', verbose_name='Клиент')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_as_consultant', to='core.employee', verbose_name='Консультант')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='consultations.consultationresult', verbose_name='Итог')),
            ],
            options={
                'verbose_name': 'Консультация',
                'verbose_name_plural': 'Консультации',
                'ordering': ['datetime_start'],
                'constraints': [models.UniqueConstraint(fields=('consultant', 'datetime_start'), name='unique_consultation_per_consultant_time')],
            },
        ),
    ]
