# Generated by Django 5.2.10 on 2026-05-02 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='transfer_reason',
            field=models.TextField(blank=True, verbose_name='Причина переноса'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='transferred_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_from', to='consultations.consultation', verbose_name='Перенесена в'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('free', 'Свободно'), ('booked', 'Записан'), ('done', 'Проведена'), ('cancelled', 'Отменена'), ('transferred', 'Перенесена')], default='free', max_length=20, verbose_name='Статус'),
        ),
    ]
