# Generated by Django 5.2.10 on 2026-06-24 07:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afd', '0007_alter_documenttemplate_kind'),
        ('core', '0024_department_is_docs_collection'),
        ('files', '0004_storedfile_bubble_id'),
        ('procedure', '0014_request_bubble_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EfrsbBankruptLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bankrupt_guid', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='GUID должника в ЕФРСБ')),
                ('match_method', models.CharField(blank=True, choices=[('inn', 'по ИНН'), ('snils', 'по СНИЛС'), ('manual', 'вручную')], max_length=16, verbose_name='Способ резолва')),
                ('match_confidence', models.CharField(blank=True, choices=[('auto', 'Автоматически (1 кандидат)'), ('confirmed', 'Подтверждено сотрудником')], max_length=16, verbose_name='Достоверность')),
                ('candidates', models.JSONField(blank=True, default=list, help_text='Сырые pageData из /v1/bankrupts при нескольких совпадениях — для ручного выбора.', verbose_name='Кандидаты (мульти-хит)')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Резолвлен в')),
                ('last_search_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний поиск должника')),
                ('next_search_at', models.DateTimeField(blank=True, null=True, verbose_name='Следующий поиск не ранее')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя выборка сообщений')),
                ('next_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Следующая выборка не ранее')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='efrsb_link', to='procedure.bankruptcycase', verbose_name='Дело')),
            ],
            options={
                'verbose_name': 'Связка должника с ЕФРСБ',
                'verbose_name_plural': 'Связки должников с ЕФРСБ',
            },
        ),
        migrations.CreateModel(
            name='EfrsbMessageType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=60, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Тип сообщения')),
                ('description', models.TextField(blank=True, verbose_name='Описание / список плейсхолдеров')),
                ('api_type', models.CharField(blank=True, help_text='Значение поля `type` read-API (напр. Meeting, Auction, TradeResult). Пусто — тип только для генерации текста, без матчинга входящих.', max_length=64, verbose_name='Тип в API ЕФРСБ')),
                ('api_type_aliases', models.JSONField(blank=True, default=list, help_text='Список других кодов API, относящихся к этому событию (напр. ["Meeting2"], ["Auction2", "ChangeAuction"]).', verbose_name='Доп. типы API (алиасы)')),
                ('applicable_kinds', models.JSONField(blank=True, default=list, help_text='Список видов процедур: restructuring / realization. Пусто — применим к обоим.', verbose_name='Применим к видам процедур')),
                ('deadline_base_key', models.CharField(blank=True, help_text='Из набора BASE_DATE_KEY_CHOICES процедуры (справочно).', max_length=32, verbose_name='Базовая дата срока (якорь)')),
                ('deadline_offset_days', models.IntegerField(default=0, help_text='Срок по 127-ФЗ = базовая дата + N дней (справочно).', verbose_name='Срок публикации, дней')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_draft', models.BooleanField(default=True, help_text='Соответствие типу API / сроки подлежат подтверждению АУ. Бейдж в UI.', verbose_name='Черновик (не подтверждён)')),
                ('isk_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='afd.isktemplate', verbose_name='Секционный шаблон (альтернатива .docx)')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='afd.documenttemplate', verbose_name='Шаблон текста (.docx)')),
            ],
            options={
                'verbose_name': 'Тип сообщения ЕФРСБ',
                'verbose_name_plural': 'Типы сообщений ЕФРСБ',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EfrsbPublication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('message', 'Сообщение'), ('report', 'Отчёт')], default='message', max_length=16, verbose_name='Вид')),
                ('origin', models.CharField(choices=[('internal', 'Наша заготовка'), ('discovered', 'Обнаружена в реестре')], default='internal', max_length=16, verbose_name='Источник')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('generated', 'Текст сформирован'), ('submitted', 'Отправлено на публикацию'), ('published', 'Опубликовано'), ('annulled', 'Аннулировано'), ('locked', 'Заблокировано')], default='draft', max_length=16, verbose_name='Статус')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('generated_text', models.TextField(blank=True, verbose_name='Текст сообщения (для ручной публикации)')),
                ('overrides', models.JSONField(blank=True, default=dict, help_text='Введённые вручную поля события (дата собрания, перечень имущества и т.п.).', verbose_name='Доп. поля события')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Текст сформирован')),
                ('fedresurs_guid', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='GUID в ЕФРСБ')),
                ('fedresurs_number', models.CharField(blank=True, max_length=64, verbose_name='Номер в ЕФРСБ')),
                ('bankrupt_guid', models.CharField(blank=True, max_length=64, verbose_name='GUID должника')),
                ('date_publish', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('api_type', models.CharField(blank=True, max_length=64, verbose_name='Тип API')),
                ('procedure_type', models.CharField(blank=True, max_length=40, verbose_name='Тип процедуры (API)')),
                ('has_violation', models.BooleanField(null=True, verbose_name='Публикация с нарушением срока')),
                ('is_annulled', models.BooleanField(default=False, verbose_name='Аннулировано')),
                ('annulment_guid', models.CharField(blank=True, max_length=64, verbose_name='GUID сообщения об аннулировании')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Заблокировано')),
                ('lock_reason', models.CharField(blank=True, max_length=255, verbose_name='Причина блокировки')),
                ('linked_guids', models.JSONField(blank=True, default=list, verbose_name='Связанные публикации (guid)')),
                ('content_xml', models.TextField(blank=True, verbose_name='Контент (XML)')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='Сырой ответ API')),
                ('discovered_at', models.DateTimeField(blank=True, null=True, verbose_name='Обнаружено в реестре')),
                ('matched_at', models.DateTimeField(blank=True, null=True, verbose_name='Привязано к заготовке')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efrsb_publications', to='procedure.bankruptcycase', verbose_name='Дело')),
                ('content_docx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='files.storedfile', verbose_name='Документ (.docx)')),
                ('content_pdf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='files.storedfile', verbose_name='Документ (PDF)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.employee', verbose_name='Кто сформировал')),
                ('message_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='efrsb.efrsbmessagetype', verbose_name='Тип сообщения')),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='efrsb_publications', to='procedure.procedure', verbose_name='Процедура')),
            ],
            options={
                'verbose_name': 'Публикация ЕФРСБ',
                'verbose_name_plural': 'Публикации ЕФРСБ',
                'ordering': ['-date_publish', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EfrsbPublicationFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, verbose_name='Имя файла')),
                ('is_safe', models.BooleanField(default=True, verbose_name='Безопасный (прошёл антивирус)')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='efrsb.efrsbpublication', verbose_name='Публикация')),
                ('stored_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='files.storedfile', verbose_name='Файл в S3')),
            ],
            options={
                'verbose_name': 'Файл публикации ЕФРСБ',
                'verbose_name_plural': 'Файлы публикаций ЕФРСБ',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='efrsbpublication',
            index=models.Index(fields=['case', 'status'], name='efrsb_efrsb_case_id_c571a0_idx'),
        ),
        migrations.AddIndex(
            model_name='efrsbpublication',
            index=models.Index(fields=['case', 'kind'], name='efrsb_efrsb_case_id_99d2d2_idx'),
        ),
        migrations.AddIndex(
            model_name='efrsbpublication',
            index=models.Index(fields=['date_publish'], name='efrsb_efrsb_date_pu_19af33_idx'),
        ),
        migrations.AddConstraint(
            model_name='efrsbpublication',
            constraint=models.UniqueConstraint(condition=models.Q(('fedresurs_guid__gt', '')), fields=('fedresurs_guid',), name='uniq_efrsb_pub_guid'),
        ),
    ]
