# Generated by Django 5.2.10 on 2026-06-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efrsb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='efrsbmessagetype',
            name='api_kind',
            field=models.CharField(choices=[('message', 'Сообщение (/v1/messages)'), ('report', 'Отчёт (/v1/reports)')], default='message', help_text='В каком разделе ЕФРСБ публикуется/ищется: сообщения или отчёты.', max_length=16, verbose_name='Раздел API'),
        ),
    ]
