# Generated by Django 5.2.10 on 2026-06-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efrsb', '0002_efrsbmessagetype_api_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='efrsbmessagetype',
            name='sets_efrsb_date',
            field=models.BooleanField(default=False, help_text='При обнаружении публикации этого типа автозаполнить Procedure.publication_efrsb_date (если ещё пусто) и пересчитать дедлайны мероприятий. 🛑 Какие типы «вводные» — подтвердить с АУ.', verbose_name='«Вводное» — проставляет дату публикации ЕФРСБ'),
        ),
    ]
