# Generated by Django 5.2.10 on 2026-06-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efrsb', '0003_efrsbmessagetype_sets_efrsb_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='efrsbmessagetype',
            name='is_bfl',
            field=models.BooleanField(default=False, help_text='Тип публикуется в банкротстве граждан. По умолчанию в селекторе показываются только такие (галочка «Показать все» открывает остальные). 🛑 Первичная разметка — заготовка, подтверждается с АУ.', verbose_name='Релевантен БФЛ (физлицо)'),
        ),
    ]
