# Generated by Django 5.2.10 on 2026-07-14 08:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efrsb', '0004_efrsbmessagetype_is_bfl'),
    ]

    operations = [
        migrations.CreateModel(
            name='EfrsbMessageSubtype',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Значение courtDecisionType в read-API (напр. PropertySale).', max_length=64, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Подтип')),
                ('applicable_kinds', models.JSONField(blank=True, default=list, help_text='restructuring / realization. Пусто — применим к обоим.', verbose_name='Применим к видам процедур')),
                ('is_bfl', models.BooleanField(default=False, help_text='Подтипы для банкротства граждан. Процедуры ЮЛ (наблюдение, внешнее управление, конкурсное производство) — снять флаг.', verbose_name='Релевантен БФЛ (физлицо)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_draft', models.BooleanField(default=True, verbose_name='Черновик (не подтверждён)')),
                ('message_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtypes', to='efrsb.efrsbmessagetype', verbose_name='Тип сообщения')),
            ],
            options={
                'verbose_name': 'Подтип сообщения ЕФРСБ',
                'verbose_name_plural': 'Подтипы сообщений ЕФРСБ',
                'ordering': ['message_type__order', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='efrsbpublication',
            name='subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='efrsb.efrsbmessagesubtype', verbose_name='Подтип (тип судебного акта)'),
        ),
        migrations.AddConstraint(
            model_name='efrsbmessagesubtype',
            constraint=models.UniqueConstraint(fields=('message_type', 'code'), name='uniq_efrsb_subtype_code'),
        ),
    ]
