# Generated by Django 5.2.10 on 2026-07-14 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afd', '0007_alter_documenttemplate_kind'),
        ('efrsb', '0005_efrsbmessagesubtype_efrsbpublication_subtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='efrsbmessagesubtype',
            name='text_template',
            field=models.TextField(blank=True, help_text='Приоритетнее шаблона типа. Плейсхолдеры {…} — из CRM.', verbose_name='Шаблон текста сообщения'),
        ),
        migrations.AddField(
            model_name='efrsbmessagetype',
            name='text_template',
            field=models.TextField(blank=True, help_text='Плейсхолдеры {…} подставляются из CRM (должник, ФУ, СРО, дело, суд). По нему кнопка «Сгенерировать текст» заполняет поле в модалке. У подтипа шаблон приоритетнее, чем у типа.', verbose_name='Шаблон текста сообщения'),
        ),
        migrations.AlterField(
            model_name='efrsbmessagetype',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='afd.documenttemplate', verbose_name='Шаблон документа (.docx)'),
        ),
    ]
