# Generated by Django 5.2.10 on 2026-08-23 12:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0037_employee_can_listen_calls_employee_sip_extension'),
        ('crm', '0102_alter_correspondence_comments'),
        ('files', '0004_storedfile_bubble_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uniqueid', models.CharField(max_length=32, unique=True, verbose_name='Uniqueid')),
                ('linkedid', models.CharField(blank=True, db_index=True, help_text='Склейка ног одного звонка (перевод, параллельный обзвон).', max_length=32, verbose_name='Linkedid')),
                ('started_at', models.DateTimeField(db_index=True, verbose_name='Начало')),
                ('direction', models.CharField(choices=[('incoming', 'Входящий'), ('outgoing', 'Исходящий'), ('internal', 'Внутренний')], db_index=True, max_length=10, verbose_name='Направление')),
                ('src', models.CharField(blank=True, max_length=80, verbose_name='Кто звонил')),
                ('dst', models.CharField(blank=True, max_length=80, verbose_name='Кому звонили')),
                ('clid', models.CharField(blank=True, max_length=120, verbose_name='CallerID')),
                ('extension', models.CharField(blank=True, db_index=True, help_text='Трёхзначный номер сотрудника на АТС.', max_length=8, verbose_name='Внутренний номер')),
                ('counterparty_phone', models.CharField(blank=True, db_index=True, help_text='Внешний номер в нормализованном виде — по нему ищется клиент.', max_length=32, verbose_name='Номер абонента')),
                ('duration', models.IntegerField(default=0, verbose_name='Длительность, с')),
                ('billsec', models.IntegerField(default=0, verbose_name='Разговор, с')),
                ('disposition', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Итог')),
                ('dcontext', models.CharField(blank=True, max_length=80, verbose_name='Контекст диалплана')),
                ('userfield', models.CharField(blank=True, help_text='Служебное поле CDR: 201:NOANSWER:19|202:ANSWER:16 и т.п.', max_length=255, verbose_name='Результат обзвона')),
                ('source_path', models.CharField(blank=True, help_text='Исходный wav (поле rec_name в CDR) — для сверки при разборе.', max_length=255, verbose_name='Путь на АТС')),
                ('has_recording_on_pbx', models.BooleanField(default=False, help_text='У неотвеченных звонков файл пустой (44 байта) и не переносится.', verbose_name='На АТС есть запись')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='crm.client', verbose_name='Клиент')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='core.employee', verbose_name='Сотрудник')),
                ('recording', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='files.storedfile', verbose_name='Запись (mp3)')),
            ],
            options={
                'verbose_name': 'Звонок',
                'verbose_name_plural': 'Звонки',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CallListen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('listened_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listens', to='telephony.call', verbose_name='Звонок')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_listens', to='core.employee', verbose_name='Кто слушал')),
            ],
            options={
                'verbose_name': 'Прослушивание записи',
                'verbose_name_plural': 'Прослушивания записей',
                'ordering': ['-listened_at'],
            },
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['client', '-started_at'], name='telephony_c_client__d904e4_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['employee', '-started_at'], name='telephony_c_employe_e498e3_idx'),
        ),
    ]
