# Generated by Django 5.2.10 on 2026-08-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0002_seed_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='outcome',
            field=models.CharField(blank=True, choices=[('answered', 'Разговор состоялся'), ('voicemail', 'Голосовое сообщение'), ('missed', 'Пропущен'), ('no_answer', 'Не ответили'), ('busy', 'Занято'), ('failed', 'Не состоялся')], db_index=True, help_text='Сводный итог по всем «ногам» звонка. 🛑 Не то же, что disposition из CDR: у звонка, ушедшего на голосовую почту, последняя нога помечена ANSWERED, хотя с клиентом никто не разговаривал.', max_length=12, verbose_name='Итог звонка'),
        ),
    ]
