# Generated by Django 5.2.10 on 2026-08-23 18:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_employee_can_listen_calls_employee_sip_extension'),
        ('crm', '0102_alter_correspondence_comments'),
        ('telephony', '0003_call_outcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingCallAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_key', models.CharField(db_index=True, help_text='DestUniqueid:внутренний — по нему приходит обновление статуса, когда звонок завершился.', max_length=64, verbose_name='Ключ ноги звонка')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Номер звонящего')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Позвонили')),
                ('answered', models.BooleanField(default=False, help_text='Проставляется по DialEnd: ANSWER — взяли, иначе пропущен.', verbose_name='Трубку взяли')),
                ('finished', models.BooleanField(default=False, verbose_name='Звонок завершён')),
                ('dismissed_at', models.DateTimeField(blank=True, null=True, verbose_name='Убрана сотрудником')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_alerts', to='crm.client', verbose_name='Клиент')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_alerts', to='core.employee', verbose_name='Кому звонили')),
            ],
            options={
                'verbose_name': 'Карточка входящего звонка',
                'verbose_name_plural': 'Карточки входящих звонков',
                'ordering': ['-started_at'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'channel_key'), name='uniq_alert_per_leg')],
            },
        ),
    ]
