# Generated by Django 5.2.10 on 2026-08-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0004_incomingcallalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingcallalert',
            name='comment',
            field=models.TextField(blank=True, default='', help_text='Короткая заметка прямо с карточки. Если клиент опознан, она же уходит в его событийку.', verbose_name='Комментарий к звонку'),
        ),
    ]
