# Generated by Django 5.2.10 on 2026-08-25 07:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_employee_notify_missed_calls'),
        ('crm', '0102_alter_correspondence_comments'),
        ('files', '0004_storedfile_bubble_id'),
        ('telephony', '0005_incomingcallalert_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllisten',
            name='call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listens', to='telephony.call', verbose_name='Звонок'),
        ),
        migrations.CreateModel(
            name='CallGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Тот же код, что диалплан передаёт скриптом уведомления: cc (колл-центр), osd (сбор документов), yuro (юротдел).', max_length=16, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('extensions', models.CharField(blank=True, default='', help_text='Через запятую: 201,202. По ним группа определяется у звонков, пришедших без сигнала от диалплана.', max_length=120, verbose_name='Внутренние номера')),
                ('notify_department', models.BooleanField(default=True, help_text='Слать пропущенные всем активным сотрудникам отдела.', verbose_name='Уведомлять весь отдел')),
                ('notify_management', models.BooleanField(default=False, help_text='Дополнительно слать руководителям (admin / head_dep / managing_partner).', verbose_name='Уведомлять руководство')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_groups', to='core.department', verbose_name='Отдел')),
                ('subscribers', models.ManyToManyField(blank=True, help_text='Кому слать сверх отдела — например, РОПу из другого отдела.', related_name='call_groups', to='core.employee', verbose_name='Дополнительные подписчики')),
            ],
            options={
                'verbose_name': 'Группа входящих звонков',
                'verbose_name_plural': 'Группы входящих звонков',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MissedCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('linkedid', models.CharField(help_text='Ключ звонка целиком (все его ноги) — по нему запись дополняется вторым источником, а не дублируется.', max_length=32, unique=True, verbose_name='Linkedid')),
                ('uniqueid', models.CharField(blank=True, max_length=32, verbose_name='Uniqueid')),
                ('occurred_at', models.DateTimeField(db_index=True, verbose_name='Когда звонили')),
                ('kind', models.CharField(choices=[('missed', 'Никто не ответил'), ('voicemail', 'Голосовое сообщение'), ('ivr', 'Бросил трубку в меню')], db_index=True, default='missed', max_length=10, verbose_name='Тип')),
                ('extension', models.CharField(blank=True, default='', max_length=8, verbose_name='Внутренний номер')),
                ('phone', models.CharField(blank=True, db_index=True, help_text='Нормализованный вид — по нему ищется клиент.', max_length=32, verbose_name='Номер звонившего')),
                ('raw_phone', models.CharField(blank=True, default='', max_length=40, verbose_name='Номер как пришёл с АТС')),
                ('voicemail_seconds', models.IntegerField(default=0, verbose_name='Длительность сообщения, с')),
                ('voicemail_file', models.CharField(blank=True, default='', help_text='Имя wav в /var/spool/asterisk/monitor — по нему агент дошлёт запись после того, как MixMonitor её закроет.', max_length=255, verbose_name='Файл на АТС')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_work', 'В работе'), ('done', 'Отработан'), ('auto_done', 'Связались (автоматически)'), ('ignored', 'Не требует ответа')], db_index=True, default='new', max_length=10, verbose_name='Статус')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='Отработан')),
                ('comment', models.TextField(blank=True, default='', help_text='Накапливаются построчно (HH:MM — текст), как на карточке звонка.', verbose_name='Заметки')),
                ('notified_at', models.DateTimeField(blank=True, help_text='🛑 Метка защищает от повторной рассылки: запись трогают оба источника, а уведомление должно уйти один раз.', null=True, verbose_name='Уведомления разосланы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missed_calls', to='core.employee', verbose_name='Кто отрабатывает')),
                ('call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missed_records', to='telephony.call', verbose_name='Звонок в журнале')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missed_calls', to='crm.client', verbose_name='Клиент')),
                ('closed_by_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closes_missed', to='telephony.call', verbose_name='Разговор, закрывший обращение')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missed_calls', to='telephony.callgroup', verbose_name='Куда звонили')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missed_calls_handled', to='core.employee', verbose_name='Кто закрыл')),
                ('recording', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voicemails', to='files.storedfile', verbose_name='Голосовое сообщение (mp3)')),
            ],
            options={
                'verbose_name': 'Пропущенный звонок',
                'verbose_name_plural': 'Пропущенные звонки',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddField(
            model_name='calllisten',
            name='missed_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listens', to='telephony.missedcall', verbose_name='Пропущенный звонок'),
        ),
        migrations.AddIndex(
            model_name='missedcall',
            index=models.Index(fields=['status', '-occurred_at'], name='telephony_m_status_8dc51c_idx'),
        ),
        migrations.AddIndex(
            model_name='missedcall',
            index=models.Index(fields=['phone', '-occurred_at'], name='telephony_m_phone_783602_idx'),
        ),
    ]
