# Generated by Django 5.2.10 on 2026-05-26 15:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0015_department_sees_all_clients_employee_is_owner'),
        ('crm', '0066_alter_clientevent_event_type'),
        ('files', '0004_storedfile_bubble_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitrCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('searching', 'Ищем дело по ФИО'), ('monitoring', 'Мониторинг дела'), ('paused', 'Приостановлен'), ('closed', 'Завершено')], default='searching', max_length=20, verbose_name='Статус мониторинга')),
                ('case_number', models.CharField(blank=True, help_text='Например: А12-1234/2026', max_length=64, verbose_name='Номер дела')),
                ('kad_url', models.URLField(blank=True, max_length=500, verbose_name='Ссылка на дело kad.arbitr.ru')),
                ('court_name', models.CharField(blank=True, help_text='Заполняется парсером со страницы дела', max_length=255, verbose_name='Суд (по факту)')),
                ('judge', models.CharField(blank=True, help_text='Заполняется парсером', max_length=255, verbose_name='Судья')),
                ('instances', models.JSONField(blank=True, default=list, help_text='Перечень инстанций где идёт спор (заполняется парсером)', verbose_name='Инстанции')),
                ('last_check_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя проверка')),
                ('last_check_ok', models.BooleanField(default=False, verbose_name='Последняя проверка успешна')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arbitr_case', to='crm.service', verbose_name='Услуга')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_arbitr_cases', to='core.employee', verbose_name='Поставил «иск отправлен»')),
            ],
            options={
                'verbose_name': 'Арбитражное дело',
                'verbose_name_plural': 'Арбитражные дела',
            },
        ),
        migrations.CreateModel(
            name='ArbitrCheckLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ts', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('state', models.CharField(choices=[('ok', 'Успех'), ('nothing', 'Изменений нет'), ('error', 'Ошибка парсера'), ('captcha', 'Капча')], max_length=16, verbose_name='Результат')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='Длительность, мс')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки/ошибка')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_logs', to='arbitr.arbitrcase', verbose_name='Дело')),
            ],
            options={
                'verbose_name': 'Лог проверки дела',
                'verbose_name_plural': 'Логи проверок дел',
                'ordering': ['-ts'],
            },
        ),
        migrations.CreateModel(
            name='ArbitrEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kad_event_id', models.CharField(blank=True, help_text='Если kad даёт стабильный идентификатор', max_length=128, verbose_name='ID события на kad')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='Дата события')),
                ('kind', models.CharField(blank=True, help_text='Определение / решение / постановление / уведомление / иное', max_length=128, verbose_name='Тип')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='Сырые поля с kad')),
                ('parsed_at', models.DateTimeField(auto_now_add=True, verbose_name='Парсинг')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='arbitr.arbitrcase', verbose_name='Дело')),
            ],
            options={
                'verbose_name': 'Событие дела',
                'verbose_name_plural': 'События дел',
                'ordering': ['-event_date', '-parsed_at'],
            },
        ),
        migrations.CreateModel(
            name='ArbitrAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, verbose_name='Имя файла')),
                ('kad_url', models.URLField(blank=True, max_length=1000, verbose_name='Ссылка на скачивание (kad)')),
                ('is_locked', models.BooleanField(default=False, help_text='Если так — файл не скачивался, доступ по запросу', verbose_name='Закрытый файл (требует ЭЦП)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stored_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arbitr_attachments', to='files.storedfile', verbose_name='Файл в S3')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='arbitr.arbitrevent', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Документ дела',
                'verbose_name_plural': 'Документы дел',
            },
        ),
        migrations.AddIndex(
            model_name='arbitrcase',
            index=models.Index(fields=['status'], name='arbitr_arbi_status_2a28f9_idx'),
        ),
        migrations.AddIndex(
            model_name='arbitrcase',
            index=models.Index(fields=['last_check_at'], name='arbitr_arbi_last_ch_ae6712_idx'),
        ),
        migrations.AddIndex(
            model_name='arbitrevent',
            index=models.Index(fields=['case', 'event_date'], name='arbitr_arbi_case_id_36c5cd_idx'),
        ),
        migrations.AddConstraint(
            model_name='arbitrevent',
            constraint=models.UniqueConstraint(condition=models.Q(('kad_event_id__gt', '')), fields=('case', 'kad_event_id'), name='uniq_arbitr_event_kad_id'),
        ),
    ]
