# Generated by Django 5.2.10 on 2026-05-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitrcase',
            name='search_hits',
            field=models.JSONField(blank=True, default=list, verbose_name='Найденные кандидаты'),
        ),
        migrations.AddField(
            model_name='arbitrcase',
            name='search_hits_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда найдены'),
        ),
    ]
