# Generated by Django 5.2.10 on 2026-06-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitr', '0002_arbitrcase_search_hits_arbitrcase_search_hits_at'),
        ('core', '0024_department_is_docs_collection'),
        ('crm', '0092_court_code_and_kinds'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitrcase',
            name='next_parse_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Следующий парсинг не раньше'),
        ),
        migrations.AddField(
            model_name='arbitrcase',
            name='next_search_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Следующий поиск не раньше'),
        ),
        migrations.AddIndex(
            model_name='arbitrcase',
            index=models.Index(fields=['next_search_at'], name='arbitr_arbi_next_se_a10c56_idx'),
        ),
        migrations.AddIndex(
            model_name='arbitrcase',
            index=models.Index(fields=['next_parse_at'], name='arbitr_arbi_next_pa_feb05c_idx'),
        ),
    ]
