# Generated by Django 5.2.10 on 2026-01-27 23:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Фамилия')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Username')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('status', models.CharField(choices=[('lead', 'Лид'), ('active', 'Активный'), ('inactive', 'Неактивный'), ('closed', 'Закрыт')], default='lead', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее сообщение')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название отдела')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер отдела')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_online', models.BooleanField(default=False, verbose_name='Онлайн')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата присоединения')),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последний визит')),
                ('clients_count', models.IntegerField(default=0, verbose_name='Количество клиентов')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operators', to='crm.department', verbose_name='Отдел')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Оператор',
                'verbose_name_plural': 'Операторы',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('document', 'Документ'), ('system', 'Системное')], default='text', max_length=20, verbose_name='Тип сообщения')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID в Telegram')),
                ('file_url', models.URLField(blank=True, verbose_name='URL файла')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='Имя файла')),
                ('direction', models.CharField(choices=[('incoming', 'Входящее'), ('outgoing', 'Исходящее')], default='incoming', max_length=20, verbose_name='Направление')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Время прочтения')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crm.client', verbose_name='Клиент')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='crm.operator', verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='assigned_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='crm.operator', verbose_name='Назначенный оператор'),
        ),
        migrations.CreateModel(
            name='OperatorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'Вход'), ('logout', 'Выход'), ('message_sent', 'Сообщение отправлено'), ('message_received', 'Сообщение получено'), ('client_assigned', 'Клиент назначен'), ('client_reassigned', 'Клиент переназначен'), ('client_status_changed', 'Статус клиента изменен'), ('note_added', 'Заметка добавлена'), ('client_unassigned', 'Клиент разъединен')], max_length=50, verbose_name='Действие')),
                ('description', models.TextField(verbose_name='Описание')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_logs', to='crm.client', verbose_name='Клиент')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='crm.message', verbose_name='Сообщение')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='crm.operator', verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'Лог оператора',
                'verbose_name_plural': 'Логи операторов',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['client', 'created_at'], name='crm_message_client__5991e6_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['operator', 'created_at'], name='crm_message_operato_cbf80a_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='crm_message_is_read_cf944a_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['telegram_id'], name='crm_client_telegra_17f8e7_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['assigned_operator', '-last_message_at'], name='crm_client_assigne_5a4cf7_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['status'], name='crm_client_status_1220b0_idx'),
        ),
        migrations.AddIndex(
            model_name='operatorlog',
            index=models.Index(fields=['operator', 'timestamp'], name='crm_operato_operato_e1cc36_idx'),
        ),
        migrations.AddIndex(
            model_name='operatorlog',
            index=models.Index(fields=['action', 'timestamp'], name='crm_operato_action_bde26d_idx'),
        ),
        migrations.AddIndex(
            model_name='operatorlog',
            index=models.Index(fields=['client', 'timestamp'], name='crm_operato_client__6b7aed_idx'),
        ),
    ]
