# Generated by Django 5.2.10 on 2026-01-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_client_patronymic'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contacts_confirmed',
            field=models.BooleanField(default=False, verbose_name='Контакты подтверждены'),
        ),
    ]
