# Generated by Django 5.2.10 on 2026-01-31 22:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_client_contacts_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('BFL', 'БФЛ'), ('DTP', 'ДТП'), ('ZALIV', 'Залив'), ('ZPP', 'ЗПП'), ('OTHER', 'Прочее')], max_length=20, verbose_name='Наименование услуги')),
                ('agent_circs', models.CharField(choices=[('ONCE_3000', 'Разово 3000'), ('PERCENT', 'Проценты'), ('INDIVIDUAL', 'Индивидуальные условия')], max_length=20, verbose_name='Условия для агента')),
                ('agent_circs_notes', models.TextField(blank=True, max_length=1000, verbose_name='Уточнения условий агента')),
                ('agent_paid', models.IntegerField(default=0, verbose_name='Выплата агентских')),
                ('special_notes', models.TextField(blank=True, max_length=1000, verbose_name='Особые отметки')),
                ('date_anketa', models.DateField(blank=True, null=True, verbose_name='Дата анкетирования')),
                ('date_dogovor', models.DateField(blank=True, null=True, verbose_name='Дата договора')),
                ('numb_dogovor', models.CharField(blank=True, max_length=50, verbose_name='Номер договора')),
                ('payment_procedure', models.CharField(choices=[('PREPAY', 'Предоплата'), ('INSTALLMENTS', 'Рассрочка'), ('POSTPAY', 'Постоплата'), ('SUCCESS_FEE', 'Гонорар успеха'), ('SUBSCRIPTION', 'Абонентская плата')], max_length=20, verbose_name='Порядок оплаты')),
                ('payment_as', models.CharField(choices=[('CASHBOX', 'Касса'), ('ACCOUNT', 'Расчетный счет'), ('CASH', 'Наличные')], max_length=20, verbose_name='Как оплачивать')),
                ('status_service', models.CharField(choices=[('LEAD', 'Лид'), ('CONTRACT', 'Заключение договора'), ('PERFORMANCE', 'Исполнение договора'), ('DEBTOR', 'Должник'), ('WARRANTY', 'Гарантийное обслуживание'), ('ARCHIVE', 'Архив')], default='LEAD', max_length=20, verbose_name='Статус услуги')),
                ('status_callcenter', models.CharField(choices=[('LEAD_CREATED', 'Лид создан'), ('NO_ANSWER', 'Недозвон'), ('BAD_LEAD', 'Неликвид'), ('LEAD_IN_WORK', 'Лид в работе'), ('REFUSED_APPOINT', 'Отказ на стадии записи на консультацию'), ('NON_TARGET', 'Нецелевой лид'), ('NOT_READY_ASSETS', 'Не готов по имуществу'), ('WANTED_FREE', 'Искал бесплатно'), ('APPOINTMENT', 'Записан на консультацию'), ('TO_CONTRACT', 'Передан на заключение договора'), ('DEAL_SUPPORT', 'Сопровождаю сделку'), ('POSTPONED', 'Отложено на потом'), ('ARCHIVE', 'Архив')], default='LEAD_CREATED', max_length=30, verbose_name='Статус в колл-центре')),
                ('status_consultant', models.CharField(choices=[('LEAD', 'Лид'), ('NO_ANSWER', 'Недозвон'), ('QUESTIONNAIRE', 'Анкетирование'), ('NON_TARGET_CLIENT', 'Нецелевой клиент'), ('APPOINTMENT', 'Запись на консультацию'), ('THINKING', 'Клиент думает'), ('TARGET_CHECK', 'Определяется целевитость клиента'), ('CONTRACT', 'Заключение договора'), ('LOST', 'Пропал'), ('CONTRACT_SIGNED', 'Договор заключен'), ('TO_LAWYERS', 'Передан в работу юристов'), ('SUPPORT', 'Сопровождаю'), ('REFUSAL', 'Отказ от сотрудничества'), ('ARCHIVE', 'Архив')], default='LEAD', max_length=30, verbose_name='Статус консультанта')),
                ('status_sbor', models.CharField(choices=[('COLLECTING', 'Сбор документов'), ('CLAIM_FILED', 'Иск подан'), ('CLAIM_RETURNED', 'Иск возвращен'), ('CLAIM_ACCEPTED', 'Иск принят'), ('TO_FIX', 'Доработать'), ('HEARING_ASSIGNED', 'Назначено СЗ'), ('PROCEDURE_STARTED', 'Введена процедура'), ('TRANSFERRED', 'Передано в другой отдел'), ('SUPPORT', 'Сопровождаю'), ('ARCHIVE', 'Архив')], default='COLLECTING', max_length=30, verbose_name='Статус сбора документов')),
                ('status_bfl', models.CharField(choices=[('INPUT', 'Ввод'), ('RESTRUCT', 'Реструктуризация'), ('REALIZATION', 'Реализация'), ('FINISHING', 'Завершение'), ('FINISHED', 'Завершен'), ('WARRANTY', 'Гарантийное обслуживание'), ('ARCHIVE', 'Архив')], default='INPUT', max_length=20, verbose_name='Статус юротдела (БФЛ)')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_services', to='crm.client', verbose_name='Агент')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='crm.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['-created_at'],
            },
        ),
    ]
