# Generated by Django 5.2.10 on 2026-02-08 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('crm', '0006_message_file'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='department',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='client',
            name='assigned_operator',
        ),
        migrations.RemoveField(
            model_name='operatorlog',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='operatorlog',
            name='client',
        ),
        migrations.RemoveField(
            model_name='operatorlog',
            name='message',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='crm_client_assigne_5a4cf7_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='crm_message_operato_cbf80a_idx',
        ),
        migrations.AddField(
            model_name='client',
            name='employees',
            field=models.ManyToManyField(blank=True, help_text='Сотрудники, работающие с клиентом', related_name='clients', to='core.employee'),
        ),
        migrations.AddField(
            model_name='message',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='core.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('document', 'Документ'), ('system', 'Системное'), ('audio', 'Аудио')], default='text', max_length=20, verbose_name='Тип сообщения'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['employee', 'created_at'], name='crm_message_employe_1e46f5_idx'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Operator',
        ),
        migrations.DeleteModel(
            name='OperatorLog',
        ),
    ]
