# Generated by Django 5.2.10 on 2026-02-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_remove_department_manager_remove_operator_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('document', 'Документ'), ('system', 'Системное'), ('audio', 'Аудио'), ('video', 'Видео')], default='text', max_length=20, verbose_name='Тип сообщения'),
        ),
    ]
