# Generated by Django 5.2.10 on 2026-03-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_message_delivered_at_message_is_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='telegram_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
