# Generated by Django 5.2.10 on 2026-03-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_message_telegram_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='max_chat_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('max', 'MAX')], default='telegram', max_length=16),
        ),
        migrations.AddField(
            model_name='message',
            name='max_message_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
