# Generated by Django 5.2.10 on 2026-03-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_client_max_chat_id_message_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='max_message_id',
            field=models.CharField(blank=True, help_text='ID сообщения в MAX', max_length=128, null=True),
        ),
    ]
