# Generated by Django 5.2.10 on 2026-03-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_alter_client_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='raw_payload',
            field=models.JSONField(blank=True, help_text='Оригинальные данные от Telegram/MAX и т.п.', null=True, verbose_name='Сырой payload канала'),
        ),
    ]
