# Generated by Django 5.2.10 on 2026-03-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_message_raw_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='client',
            name='birth_place',
            field=models.CharField(blank=True, max_length=500, verbose_name='Место рождения'),
        ),
        migrations.AddField(
            model_name='client',
            name='inn',
            field=models.CharField(blank=True, max_length=12, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='client',
            name='passport_issued_by',
            field=models.CharField(blank=True, max_length=500, verbose_name='Кем выдан'),
        ),
        migrations.AddField(
            model_name='client',
            name='passport_issued_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AddField(
            model_name='client',
            name='passport_number',
            field=models.CharField(blank=True, max_length=6, verbose_name='Номер паспорта'),
        ),
        migrations.AddField(
            model_name='client',
            name='passport_series',
            field=models.CharField(blank=True, max_length=4, verbose_name='Серия паспорта'),
        ),
        migrations.AddField(
            model_name='client',
            name='snils',
            field=models.CharField(blank=True, max_length=14, verbose_name='СНИЛС'),
        ),
    ]
