# Generated by Django 5.2.10 on 2026-03-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_client_birth_date_client_birth_place_client_inn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birth_place',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Место рождения'),
        ),
    ]
