# Generated by Django 5.2.10 on 2026-03-27 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_alter_client_birth_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='crm.message', verbose_name='Ответ на сообщение'),
        ),
    ]
