# Generated by Django 5.2.10 on 2026-03-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_message_reply_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Номер региона')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование региона')),
                ('court_name', models.CharField(max_length=500, verbose_name='Наименование суда')),
                ('court_address', models.TextField(verbose_name='Адрес суда')),
                ('court_payment_details', models.TextField(help_text='БИК, расчётный счёт, получатель, КБК и прочие реквизиты', verbose_name='Реквизиты суда для госпошлины')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ['number'],
            },
        ),
    ]
