# Generated by Django 5.2.10 on 2026-04-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reactions',
            field=models.JSONField(blank=True, default=dict, help_text='Реакции на сообщение, например: {"👍": 3, "❤️": 1}', verbose_name='Реакции'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('document', 'Документ'), ('system', 'Системное'), ('audio', 'Аудио'), ('video', 'Видео'), ('voice', 'Голосовое')], default='text', max_length=20, verbose_name='Тип сообщения'),
        ),
    ]
