# Generated by Django 5.2.10 on 2026-04-15 14:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_message_reactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_type', models.CharField(choices=[('default', 'По умолчанию'), ('registration', 'Адрес регистрации'), ('actual', 'Адрес фактического проживания'), ('postal', 'Почтовый адрес'), ('other', 'Иное')], default='default', max_length=20, verbose_name='Тип адреса')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='Комментарий')),
                ('result', models.TextField(blank=True, verbose_name='Полный адрес (стандартизированный)')),
                ('source', models.TextField(blank=True, verbose_name='Исходный ввод')),
                ('postal_code', models.CharField(blank=True, max_length=6, verbose_name='Индекс')),
                ('country', models.CharField(blank=True, default='Россия', max_length=120, verbose_name='Страна')),
                ('country_iso_code', models.CharField(blank=True, max_length=2, verbose_name='ISO-код страны')),
                ('federal_district', models.CharField(blank=True, max_length=255, verbose_name='Федеральный округ')),
                ('region_fias_id', models.CharField(blank=True, max_length=36, verbose_name='ФИАС ID региона')),
                ('region_kladr_id', models.CharField(blank=True, max_length=19, verbose_name='КЛАДР ID региона')),
                ('region_with_type', models.CharField(blank=True, max_length=255, verbose_name='Регион с типом')),
                ('region_type_full', models.CharField(blank=True, max_length=50, verbose_name='Тип региона')),
                ('region', models.CharField(blank=True, max_length=255, verbose_name='Регион')),
                ('area_fias_id', models.CharField(blank=True, max_length=36, verbose_name='ФИАС ID района')),
                ('area_with_type', models.CharField(blank=True, max_length=255, verbose_name='Район с типом')),
                ('area_type_full', models.CharField(blank=True, max_length=50, verbose_name='Тип района')),
                ('area', models.CharField(blank=True, max_length=255, verbose_name='Район')),
                ('city_fias_id', models.CharField(blank=True, max_length=36, verbose_name='ФИАС ID города')),
                ('city_kladr_id', models.CharField(blank=True, max_length=19, verbose_name='КЛАДР ID города')),
                ('city_with_type', models.CharField(blank=True, max_length=255, verbose_name='Город с типом')),
                ('city_type_full', models.CharField(blank=True, max_length=50, verbose_name='Тип города')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='Город')),
                ('city_district_with_type', models.CharField(blank=True, max_length=255, verbose_name='Район города с типом')),
                ('settlement_fias_id', models.CharField(blank=True, max_length=36, verbose_name='ФИАС ID н.п.')),
                ('settlement_with_type', models.CharField(blank=True, max_length=255, verbose_name='Нас. пункт с типом')),
                ('settlement_type_full', models.CharField(blank=True, max_length=50, verbose_name='Тип нас. пункта')),
                ('settlement', models.CharField(blank=True, max_length=255, verbose_name='Населённый пункт')),
                ('street_fias_id', models.CharField(blank=True, max_length=36, verbose_name='ФИАС ID улицы')),
                ('street_with_type', models.CharField(blank=True, max_length=255, verbose_name='Улица с типом')),
                ('street_type_full', models.CharField(blank=True, max_length=50, verbose_name='Тип улицы')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Улица')),
                ('house_fias_id', models.CharField(blank=True, max_length=36, verbose_name='ФИАС ID дома')),
                ('house_type_full', models.CharField(blank=True, max_length=50, verbose_name='Тип дома')),
                ('house', models.CharField(blank=True, max_length=50, verbose_name='Дом')),
                ('block_type_full', models.CharField(blank=True, max_length=50, verbose_name='Тип корпуса/строения')),
                ('block', models.CharField(blank=True, max_length=50, verbose_name='Корпус/строение')),
                ('entrance', models.CharField(blank=True, max_length=10, verbose_name='Подъезд')),
                ('floor', models.CharField(blank=True, max_length=10, verbose_name='Этаж')),
                ('flat_type_full', models.CharField(blank=True, max_length=50, verbose_name='Тип помещения')),
                ('flat', models.CharField(blank=True, max_length=50, verbose_name='Квартира/офис')),
                ('fias_id', models.CharField(blank=True, max_length=36, verbose_name='ФИАС ID')),
                ('fias_level', models.CharField(blank=True, max_length=2, verbose_name='Уровень детализации ФИАС')),
                ('kladr_id', models.CharField(blank=True, max_length=19, verbose_name='КЛАДР ID')),
                ('geo_lat', models.CharField(blank=True, max_length=15, verbose_name='Широта')),
                ('geo_lon', models.CharField(blank=True, max_length=15, verbose_name='Долгота')),
                ('qc_geo', models.CharField(blank=True, max_length=1, verbose_name='Код точности координат')),
                ('qc_complete', models.CharField(blank=True, max_length=1, verbose_name='Код полноты')),
                ('qc_house', models.CharField(blank=True, max_length=1, verbose_name='Код проверки дома')),
                ('qc', models.CharField(blank=True, max_length=1, verbose_name='Код качества')),
                ('okato', models.CharField(blank=True, max_length=11, verbose_name='ОКАТО')),
                ('oktmo', models.CharField(blank=True, max_length=11, verbose_name='ОКТМО')),
                ('tax_office', models.CharField(blank=True, max_length=4, verbose_name='Код ИФНС')),
                ('timezone', models.CharField(blank=True, max_length=50, verbose_name='Часовой пояс')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='crm.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'ordering': ['address_type'],
            },
        ),
    ]
