# Generated by Django 5.2.10 on 2026-04-16 11:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_address_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('ooo', 'ООО'), ('ip', 'ИП'), ('ao', 'АО'), ('pao', 'ПАО'), ('other', 'Иное')], default='ooo', max_length=10, verbose_name='Форма')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('short_name', models.CharField(blank=True, max_length=255, verbose_name='Краткое наименование')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=15, verbose_name='ОГРН')),
                ('okpo', models.CharField(blank=True, max_length=14, verbose_name='ОКПО')),
                ('okved', models.CharField(blank=True, max_length=10, verbose_name='ОКВЭД')),
                ('legal_address', models.TextField(blank=True, verbose_name='Юридический адрес')),
                ('actual_address', models.TextField(blank=True, verbose_name='Фактический адрес')),
                ('postal_address', models.TextField(blank=True, verbose_name='Почтовый адрес')),
                ('director_name', models.CharField(blank=True, max_length=255, verbose_name='Руководитель')),
                ('director_title', models.CharField(blank=True, max_length=255, verbose_name='Должность руководителя')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Банк')),
                ('bik', models.CharField(blank=True, max_length=9, verbose_name='БИК')),
                ('correspondent_account', models.CharField(blank=True, max_length=20, verbose_name='Корр. счёт')),
                ('settlement_account', models.CharField(blank=True, max_length=20, verbose_name='Расчётный счёт')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Юридическое лицо',
                'verbose_name_plural': 'Юридические лица',
                'ordering': ['name'],
            },
        ),
    ]
