# Generated by Django 5.2.10 on 2026-04-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_client_employee_through'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='status',
            field=models.CharField(choices=[('active', 'Действующая'), ('liquidation', 'В ликвидации'), ('bankruptcy', 'Банкротство'), ('liquidated', 'Ликвидирована')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
