# Generated by Django 5.2.10 on 2026-04-22 06:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_legalentity_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalEntityKind',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование типа')),
                ('short_name', models.CharField(max_length=50, verbose_name='Сокращённое наименование')),
            ],
            options={
                'verbose_name': 'Тип юридического лица',
                'verbose_name_plural': 'Типы юридических лиц',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='legalentity',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legal_entities', to='crm.legalentitykind', verbose_name='Тип юридического лица'),
        ),
    ]
