# Generated by Django 5.2.10 on 2026-04-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_seed_legal_entity_kinds'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='brand',
            field=models.CharField(blank=True, max_length=255, verbose_name='Бренд'),
        ),
    ]
