# Generated by Django 5.2.10 on 2026-04-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0036_address_client_nullable_region_court_address_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='court_deposit_details',
            field=models.TextField(blank=True, default='', help_text='Реквизиты депозитного счёта суда (для внесения денежных средств на депозит)', verbose_name='Реквизиты суда для оплаты депозита'),
        ),
    ]
