# Generated by Django 5.2.10 on 2026-04-24 11:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_references_icon_emoji'),
        ('crm', '0037_add_court_deposit_details'),
        ('files', '0002_storedfile_content_type_storedfile_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProcedure',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное наименование')),
                ('short_name', models.CharField(max_length=50, verbose_name='Сокращённое наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Порядок оплаты',
                'verbose_name_plural': 'Порядок оплаты',
                'ordering': ['short_name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCommonStatus',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Наименование статуса')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Общий статус услуги',
                'verbose_name_plural': 'Общие статусы услуг',
                'ordering': ['service_name', 'order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='service',
            name='agent_circs_notes',
        ),
        migrations.RemoveField(
            model_name='service',
            name='agent_paid',
        ),
        migrations.RemoveField(
            model_name='service',
            name='date_anketa',
        ),
        migrations.RemoveField(
            model_name='service',
            name='payment_as',
        ),
        migrations.RemoveField(
            model_name='service',
            name='special_notes',
        ),
        migrations.RemoveField(
            model_name='service',
            name='status_bfl',
        ),
        migrations.RemoveField(
            model_name='service',
            name='status_callcenter',
        ),
        migrations.RemoveField(
            model_name='service',
            name='status_consultant',
        ),
        migrations.RemoveField(
            model_name='service',
            name='status_sbor',
        ),
        migrations.RemoveField(
            model_name='service',
            name='status_service',
        ),
        migrations.AddField(
            model_name='service',
            name='agent_notes',
            field=models.TextField(blank=True, verbose_name='Комментарии по работе с агентом'),
        ),
        migrations.AddField(
            model_name='service',
            name='agent_once_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма разовой выплаты агенту'),
        ),
        migrations.AddField(
            model_name='service',
            name='agent_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Процент выплаты агенту (от денег клиента)'),
        ),
        migrations.AddField(
            model_name='service',
            name='contract_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_services', to='files.storedfile', verbose_name='Файл договора'),
        ),
        migrations.AddField(
            model_name='service',
            name='contract_seq',
            field=models.PositiveIntegerField(blank=True, help_text='Начинается с 1000; формируется автоматически при сохранении', null=True, unique=True, verbose_name='Счётчик номера договора'),
        ),
        migrations.AddField(
            model_name='service',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания оказания услуг'),
        ),
        migrations.AddField(
            model_name='service',
            name='date_executed',
            field=models.DateField(blank=True, null=True, verbose_name='Дата исполнения услуг по договору'),
        ),
        migrations.AddField(
            model_name='service',
            name='date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала оказания услуг'),
        ),
        migrations.AddField(
            model_name='service',
            name='date_terminated',
            field=models.DateField(blank=True, null=True, verbose_name='Дата расторжения договора'),
        ),
        migrations.AddField(
            model_name='service',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='crm.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='service',
            name='agent_circs',
            field=models.CharField(blank=True, choices=[('ONCE', 'Разовая выплата'), ('PERCENT', 'Процент'), ('INDIVIDUAL', 'Индивидуальные условия')], default='', max_length=20, verbose_name='Условия для агента'),
        ),
        migrations.AlterField(
            model_name='service',
            name='numb_dogovor',
            field=models.CharField(blank=True, help_text="Автоматически '1000-БФЛ' или вводится вручную", max_length=50, verbose_name='Номер договора'),
        ),
        migrations.AlterField(
            model_name='service',
            name='payment_procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='crm.paymentprocedure', verbose_name='Порядок оплаты'),
        ),
        migrations.AddField(
            model_name='service',
            name='common_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='crm.servicecommonstatus', verbose_name='Общий статус услуги'),
        ),
        migrations.CreateModel(
            name='ServiceEmployeeState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_states', to='core.employee', verbose_name='Сотрудник')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_states', to='crm.service', verbose_name='Услуга')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.employee', verbose_name='Кем обновлено')),
            ],
            options={
                'verbose_name': 'Статус исполнителя',
                'verbose_name_plural': 'Статусы исполнителей',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='assigned_services', through='crm.ServiceEmployeeState', through_fields=('service', 'employee'), to='core.employee', verbose_name='Исполнители'),
        ),
        migrations.CreateModel(
            name='ServiceEmployeeStatus',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Наименование статуса')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_statuses', to='core.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Статус услуги сотрудника',
                'verbose_name_plural': 'Статусы услуг сотрудников',
                'ordering': ['employee', 'service_name', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='serviceemployeestate',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='states', to='crm.serviceemployeestatus', verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='ServiceName',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное наименование')),
                ('short_name', models.CharField(max_length=50, verbose_name='Сокращённое наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('departments', models.ManyToManyField(blank=True, related_name='service_names', to='core.department', verbose_name='Отделы')),
            ],
            options={
                'verbose_name': 'Наименование услуги',
                'verbose_name_plural': 'Наименования услуг',
                'ordering': ['short_name'],
            },
        ),
        migrations.AddField(
            model_name='serviceemployeestatus',
            name='service_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_statuses', to='crm.servicename', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='servicecommonstatus',
            name='service_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_statuses', to='crm.servicename', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='crm.servicename', verbose_name='Услуга'),
        ),
        migrations.CreateModel(
            name='ServiceTag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Наименование тега')),
                ('color', models.CharField(blank=True, default='', help_text='Например: badge-warning, badge-error, badge-info', max_length=30, verbose_name='Цвет (tailwind class)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_tags', to='core.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['employee', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('status_change', 'Смена статуса сотрудника'), ('common_status_change', 'Смена общего статуса'), ('tag_added', 'Тег добавлен'), ('tag_removed', 'Тег удалён'), ('assigned', 'Сотрудник назначен'), ('unassigned', 'Сотрудник снят')], max_length=30, verbose_name='Действие')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_logs', to='core.employee', verbose_name='Сотрудник')),
                ('new_common_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.servicecommonstatus', verbose_name='Новый общий статус')),
                ('new_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.serviceemployeestatus', verbose_name='Новый статус')),
                ('old_common_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.servicecommonstatus', verbose_name='Старый общий статус')),
                ('old_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.serviceemployeestatus', verbose_name='Старый статус')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='crm.service', verbose_name='Услуга')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.servicetag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Лог услуги',
                'verbose_name_plural': 'Логи услуг',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTagAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_tag_assignments', to='core.employee', verbose_name='Сотрудник')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments', to='crm.service', verbose_name='Услуга')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='crm.servicetag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Назначение тега',
                'verbose_name_plural': 'Назначения тегов',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='services', through='crm.ServiceTagAssignment', to='crm.servicetag', verbose_name='Теги'),
        ),
        migrations.AddConstraint(
            model_name='serviceemployeestate',
            constraint=models.UniqueConstraint(fields=('service', 'employee'), name='unique_state_per_service_employee'),
        ),
        migrations.AddConstraint(
            model_name='serviceemployeestatus',
            constraint=models.UniqueConstraint(fields=('employee', 'service_name', 'name'), name='unique_emp_status_per_emp_service'),
        ),
        migrations.AddConstraint(
            model_name='servicecommonstatus',
            constraint=models.UniqueConstraint(fields=('service_name', 'name'), name='unique_common_status_per_service'),
        ),
        migrations.AddConstraint(
            model_name='servicetag',
            constraint=models.UniqueConstraint(fields=('employee', 'name'), name='unique_tag_per_employee'),
        ),
        migrations.AddIndex(
            model_name='servicelog',
            index=models.Index(fields=['service', 'created_at'], name='crm_service_service_5c9e38_idx'),
        ),
        migrations.AddIndex(
            model_name='servicelog',
            index=models.Index(fields=['employee', 'created_at'], name='crm_service_employe_641ede_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicetagassignment',
            constraint=models.UniqueConstraint(fields=('service', 'employee', 'tag'), name='unique_tag_assignment'),
        ),
    ]
