# Generated by Django 5.2.10 on 2026-04-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_paymentprocedure_servicecommonstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='contract_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Цена договора, ₽'),
        ),
    ]
