# Generated by Django 5.2.10 on 2026-05-02 14:51

from django.db import migrations, models


def migrate_inactive(apps, schema_editor):
    apps.get_model("crm", "Client").objects.filter(status="inactive").update(status="archive")


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0040_serviceemployeestatus_common_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('unknown', 'Неизвестный'), ('lead', 'Лид'), ('active', 'Активный'), ('closed', 'Закрыт'), ('archive', 'Архивный')], default='lead', max_length=20, verbose_name='Статус'),
        ),
        migrations.RunPython(migrate_inactive, migrations.RunPython.noop),
    ]
