# Generated by Django 5.2.10 on 2026-05-02 15:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_seed_menu_legal_entities'),
        ('crm', '0041_client_status_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('first_contact', 'Первое обращение'), ('status_change', 'Смена статуса'), ('note', 'Заметка'), ('contract_created', 'Заключение договора'), ('contract_terminated', 'Расторжение договора'), ('employee_assigned', 'Назначен сотрудник'), ('employee_removed', 'Сотрудник снят'), ('system', 'Системное событие')], default='note', max_length=30, verbose_name='Тип события')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('old_value', models.CharField(blank=True, max_length=255, verbose_name='Старое значение')),
                ('new_value', models.CharField(blank=True, max_length=255, verbose_name='Новое значение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='crm.client', verbose_name='Клиент')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_events', to='core.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Событие клиента',
                'verbose_name_plural': 'События клиентов',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'created_at'], name='crm_cliente_client__30bc81_idx')],
            },
        ),
    ]
