# Generated by Django 5.2.10 on 2026-05-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0044_client_event_dialog_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientevent',
            name='event_type',
            field=models.CharField(choices=[('first_contact', 'Первое обращение'), ('status_change', 'Смена статуса'), ('note', 'Заметка'), ('contract_created', 'Заключение договора'), ('contract_terminated', 'Расторжение договора'), ('employee_assigned', 'Назначен сотрудник'), ('employee_removed', 'Сотрудник снят'), ('dept_assigned', 'Передан в работу отдела'), ('claim_filed', 'Подан иск в суд'), ('hearing_scheduled', 'Назначено судебное заседание'), ('procedure_started', 'Введена процедура'), ('procedure_ended', 'Окончена процедура'), ('dialog_started', 'Начат диалог'), ('dialog_ended', 'Окончен диалог'), ('file_received', 'Получен файл'), ('file_sent', 'Отправлен файл'), ('letter_outgoing', 'Направлено исходящее письмо'), ('letter_incoming', 'Получено входящее письмо'), ('system', 'Системное событие')], default='note', max_length=30, verbose_name='Тип события'),
        ),
    ]
