# Generated by Django 5.2.10 on 2026-05-02 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_seed_menu_legal_entities'),
        ('crm', '0045_client_event_file_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecommonstatus',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_statuses', to='core.department', verbose_name='Ответственный отдел'),
        ),
    ]
