# Generated by Django 5.2.10 on 2026-05-13 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0050_client_is_identified'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='client',
            name='crm_client_is_iden_idx',
        ),
    ]
