# Generated by Django 5.2.10 on 2026-05-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0051_remove_client_crm_client_is_iden_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='additional_costs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Доп. расходы, ₽'),
        ),
        migrations.AddField(
            model_name='service',
            name='doc_collection',
            field=models.DecimalField(decimal_places=2, default=7500, max_digits=14, verbose_name='Сбор документов, ₽'),
        ),
        migrations.AddField(
            model_name='service',
            name='fu_fee',
            field=models.DecimalField(decimal_places=2, default=25000, max_digits=14, verbose_name='Вознаграждение ФУ, ₽'),
        ),
        migrations.AddField(
            model_name='service',
            name='installment_months',
            field=models.PositiveSmallIntegerField(default=6, verbose_name='Рассрочка, мес'),
        ),
        migrations.AddField(
            model_name='service',
            name='legal_services_amount',
            field=models.DecimalField(decimal_places=2, default=72000, max_digits=14, verbose_name='Юруслуги по договору, ₽'),
        ),
        migrations.AddField(
            model_name='service',
            name='postal_costs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Почтовые расходы, ₽'),
        ),
        migrations.AddField(
            model_name='service',
            name='procedure_costs',
            field=models.DecimalField(decimal_places=2, default=20000, max_digits=14, verbose_name='Расходы на процедуру, ₽'),
        ),
        migrations.AddField(
            model_name='service',
            name='state_duty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Гос. пошлина, ₽'),
        ),
    ]
