# Generated by Django 5.2.10 on 2026-05-18 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_employee_role'),
        ('crm', '0052_service_additional_costs_service_doc_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='schedule_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_created', to='core.employee', verbose_name='Кто составил график'),
        ),
        migrations.AddField(
            model_name='service',
            name='schedule_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата составления графика платежей'),
        ),
        migrations.AddField(
            model_name='service',
            name='schedule_fu_offset',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Вознаграждение ФУ через, мес'),
        ),
        migrations.AddField(
            model_name='service',
            name='schedule_legal_offset',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Первый платёж за юруслуги через, мес'),
        ),
        migrations.AddField(
            model_name='service',
            name='schedule_procedure_offset',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Расходы на процедуру через, мес'),
        ),
        migrations.AddField(
            model_name='service',
            name='schedule_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_updated', to='core.employee', verbose_name='Кто изменил график'),
        ),
    ]
