# Generated by Django 5.2.10 on 2026-05-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0053_service_schedule_created_by_service_schedule_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientevent',
            name='event_type',
            field=models.CharField(choices=[('first_contact', 'Первое обращение'), ('status_change', 'Смена статуса'), ('client_identified', 'Клиент идентифицирован'), ('note', 'Заметка'), ('contract_created', 'Заключение договора'), ('contract_terminated', 'Расторжение договора'), ('employee_assigned', 'Назначен сотрудник'), ('employee_removed', 'Сотрудник снят'), ('dept_assigned', 'Передан в работу отдела'), ('claim_filed', 'Подан иск в суд'), ('hearing_scheduled', 'Назначено судебное заседание'), ('procedure_started', 'Введена процедура'), ('procedure_ended', 'Окончена процедура'), ('dialog_started', 'Начат диалог'), ('dialog_ended', 'Окончен диалог'), ('file_received', 'Получен файл'), ('file_sent', 'Отправлен файл'), ('letter_outgoing', 'Направлено исходящее письмо'), ('letter_incoming', 'Получено входящее письмо'), ('service_created', 'Услуга добавлена'), ('service_deleted', 'Услуга удалена'), ('consultation_booked', 'Записан на консультацию'), ('consultation_result', 'Результат консультации'), ('consultation_transferred', 'Консультация перенесена'), ('consultation_edited', 'Консультация изменена'), ('questionnaire_created', 'Анкета создана'), ('questionnaire_edited', 'Анкета отредактирована'), ('questionnaire_deleted', 'Анкета удалена'), ('schedule_created', 'Составлен график платежей'), ('schedule_updated', 'Изменён график платежей'), ('payment_created', 'Внесён платёж'), ('payment_edited', 'Платёж отредактирован'), ('payment_deleted', 'Платёж удалён'), ('system', 'Системное событие')], default='note', max_length=30, verbose_name='Тип события'),
        ),
    ]
