# Generated by Django 5.2.10 on 2026-05-19 12:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_employee_role'),
        ('crm', '0056_alter_clientevent_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('body', models.TextField(help_text='Плейсхолдеры: {{ client.first_name }}, {{ client.last_name }}, {{ service.numb_dogovor }}, {{ employee.user.first_name }}. Для WA-шаблонов переменные обозначаются {{1}}, {{2}} согласно требованиям Meta.', verbose_name='Текст шаблона')),
                ('channels', models.JSONField(default=list, help_text='Список из telegram / max / whatsapp.', verbose_name='Каналы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('whatsapp_meta_id', models.CharField(blank=True, default='', max_length=200, verbose_name='Meta template ID')),
                ('whatsapp_meta_status', models.CharField(blank=True, choices=[('draft', 'Черновик'), ('pending', 'На модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], default='draft', max_length=20, verbose_name='Статус модерации Meta')),
                ('whatsapp_meta_rejection', models.TextField(blank=True, default='', verbose_name='Причина отклонения Meta')),
                ('whatsapp_category', models.CharField(blank=True, choices=[('UTILITY', 'Сервисный (UTILITY)'), ('MARKETING', 'Маркетинговый (MARKETING)'), ('AUTHENTICATION', 'Аутентификация (AUTHENTICATION)')], default='', max_length=20, verbose_name='Категория WA')),
                ('whatsapp_language', models.CharField(blank=True, default='ru', max_length=10, verbose_name='Язык WA')),
                ('whatsapp_params_schema', models.JSONField(blank=True, default=list, help_text='Список объектов вида {"placeholder": "{{1}}", "example": "Иван"}.', verbose_name='Описание параметров WA')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_templates_created', to='core.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_templates_updated', to='core.employee')),
            ],
            options={
                'verbose_name': 'Шаблон сообщения',
                'verbose_name_plural': 'Шаблоны сообщений',
                'ordering': ['name'],
            },
        ),
    ]
