# Generated by Django 5.2.10 on 2026-05-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0057_messagetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='whatsapp_phone',
            field=models.CharField(blank=True, help_text='Например, 79991234567', max_length=20, null=True, unique=True, verbose_name='WhatsApp phone (E.164 без +)'),
        ),
        migrations.AddField(
            model_name='message',
            name='whatsapp_message_id',
            field=models.CharField(blank=True, help_text='ID сообщения в WhatsApp (Meta wamid)', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('max', 'MAX'), ('whatsapp', 'WhatsApp')], default='telegram', max_length=16),
        ),
    ]
