# Generated by Django 5.2.10 on 2026-05-22 07:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0058_client_whatsapp_phone_message_whatsapp_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bubble_id',
            field=models.CharField(blank=True, help_text='Идентификатор записи в исходной CRM на bubble.io', max_length=64, null=True, unique=True, verbose_name='Bubble ID'),
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужчина'), ('female', 'Женщина')], default='', max_length=10, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_married',
            field=models.BooleanField(default=False, verbose_name='В браке'),
        ),
        migrations.AddField(
            model_name='client',
            name='referral_source',
            field=models.CharField(blank=True, default='', help_text='Откуда клиент узнал о компании', max_length=255, verbose_name='Источник привлечения'),
        ),
        migrations.AddField(
            model_name='client',
            name='spouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spouse_of', to='crm.client', verbose_name='Супруг(а)'),
        ),
        migrations.AddField(
            model_name='message',
            name='bubble_id',
            field=models.CharField(blank=True, help_text='ID записи MessageWSP в исходной CRM на bubble.io', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='bubble_id',
            field=models.CharField(blank=True, help_text='Идентификатор ProjectBFL в исходной CRM на bubble.io', max_length=64, null=True, unique=True, verbose_name='Bubble ID'),
        ),
        migrations.CreateModel(
            name='ClientNameHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Прежняя фамилия')),
                ('first_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Прежнее имя')),
                ('patronymic', models.CharField(blank=True, default='', max_length=255, verbose_name='Прежнее отчество')),
                ('note', models.CharField(blank=True, default='', max_length=500, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_history', to='crm.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Прежнее ФИО клиента',
                'verbose_name_plural': 'История ФИО клиентов',
                'ordering': ['client', '-created_at'],
            },
        ),
    ]
