# Generated by Django 5.2.10 on 2026-05-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0059_client_bubble_id_client_gender_client_is_married_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('unknown', 'Неизвестный'), ('lead', 'Лид'), ('active', 'Активный'), ('closed', 'Закрыт'), ('archive', 'Архивный'), ('refused', 'Отказники'), ('to_delete', 'На удаление')], default='lead', max_length=20, verbose_name='Статус'),
        ),
    ]
