# Generated by Django 5.2.10 on 2026-05-25 07:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0062_alter_clientevent_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPhone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(help_text='E.164 без «+», например 79991234567', max_length=20, verbose_name='Номер телефона')),
                ('purpose', models.CharField(choices=[('primary', 'Основной'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('max', 'MAX'), ('additional', 'Дополнительный')], default='additional', max_length=20, verbose_name='Назначение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='crm.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Телефон клиента',
                'verbose_name_plural': 'Телефоны клиента',
                'ordering': ['purpose', 'phone'],
                'indexes': [models.Index(fields=['phone'], name='crm_clientp_phone_ef785a_idx'), models.Index(fields=['client', 'purpose'], name='crm_clientp_client__34f8bd_idx')],
                'constraints': [models.UniqueConstraint(fields=('phone', 'purpose'), name='uniq_clientphone_phone_purpose')],
            },
        ),
    ]
