# Generated by Django 5.2.10 on 2026-05-25 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0063_clientphone'),
    ]

    operations = [
    ]
