# Generated by Django 5.2.10 on 2026-05-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0066_alter_clientevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='bubble_id',
            field=models.CharField(blank=True, help_text='ID соответствующей записи в Bubble (для импорта Organization).', max_length=64, null=True, unique=True, verbose_name='Bubble ID'),
        ),
        migrations.AddField(
            model_name='legalentitykind',
            name='bubble_id',
            field=models.CharField(blank=True, help_text='ID соответствующей записи в Bubble (для импорта).', max_length=64, null=True, unique=True, verbose_name='Bubble ID'),
        ),
    ]
