# Generated by Django 5.2.10 on 2026-05-28 11:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_arbitr_menu_attach_to_configs'),
        ('crm', '0067_legalentity_bubble_id_legalentitykind_bubble_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kreditor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bubble_id', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Bubble ID')),
                ('name_manual', models.CharField(blank=True, help_text='Заполняется, когда субъект ещё не привязан к справочнику.', max_length=500, verbose_name='Имя кредитора (свободный ввод)')),
                ('source', models.CharField(choices=[('anketa', 'Из анкеты клиента'), ('verified', 'По полученным справкам'), ('manual', 'Добавлен вручную')], default='anketa', max_length=12, verbose_name='Источник')),
                ('debt_basis', models.TextField(blank=True, verbose_name='Основание долга')),
                ('sum_anketa', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Сумма со слов клиента (анкета)')),
                ('sum_verified', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Сумма по справке')),
                ('current_status', models.CharField(blank=True, choices=[('', '—'), ('claim_filed', 'Подано заявление о включении в РТК'), ('included', 'Включено в РТК'), ('paid_partial', 'Оплачено частично'), ('paid_full', 'Оплачено полностью')], default='', max_length=20, verbose_name='Текущий статус по процедуре')),
                ('current_status_date', models.DateField(blank=True, null=True, verbose_name='Дата текущего статуса')),
                ('secured_by_collateral', models.BooleanField(default=False, verbose_name='Обеспечено залогом')),
                ('collateral_description', models.TextField(blank=True, verbose_name='Описание залога')),
                ('client_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_kreditor_for', to='crm.client', verbose_name='Физлицо (кредитор)')),
                ('legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kreditor_of', to='crm.legalentity', verbose_name='Юрлицо/ИП (кредитор)')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kreditors', to='crm.service', verbose_name='Услуга БФЛ')),
            ],
            options={
                'verbose_name': 'Кредитор',
                'verbose_name_plural': 'Кредиторы',
                'ordering': ['-sum_anketa', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='KreditorStatusEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('claim_filed', 'Подано заявление о включении в РТК'), ('included', 'Включено в РТК'), ('paid_partial', 'Оплачено частично'), ('paid_full', 'Оплачено полностью')], max_length=20, verbose_name='Статус')),
                ('date', models.DateField(verbose_name='Дата')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Сумма')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kreditor_events', to='core.employee', verbose_name='Сотрудник')),
                ('kreditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='crm.kreditor', verbose_name='Кредитор')),
            ],
            options={
                'verbose_name': 'Событие смены статуса кредитора',
                'verbose_name_plural': 'События смены статусов кредиторов',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='kreditor',
            index=models.Index(fields=['service'], name='crm_kredito_service_2394df_idx'),
        ),
        migrations.AddIndex(
            model_name='kreditor',
            index=models.Index(fields=['current_status'], name='crm_kredito_current_ed0b30_idx'),
        ),
        migrations.AddConstraint(
            model_name='kreditor',
            constraint=models.CheckConstraint(condition=models.Q(('legal_entity__isnull', False), ('client_person__isnull', False), models.Q(('name_manual', ''), _negated=True), _connector='OR'), name='kreditor_has_subject'),
        ),
    ]
