# Generated by Django 5.2.10 on 2026-05-28 14:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0068_kreditor_kreditorstatusevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientevent',
            name='bubble_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Bubble ID'),
        ),
        migrations.AlterField(
            model_name='clientevent',
            name='event_type',
            field=models.CharField(choices=[('first_contact', 'Первое обращение'), ('status_change', 'Смена статуса'), ('client_identified', 'Клиент идентифицирован'), ('note', 'Заметка'), ('contract_created', 'Заключение договора'), ('contract_terminated', 'Расторжение договора'), ('employee_assigned', 'Назначен сотрудник'), ('employee_removed', 'Сотрудник снят'), ('dept_assigned', 'Передан в работу отдела'), ('claim_filed', 'Подан иск в суд'), ('hearing_scheduled', 'Назначено судебное заседание'), ('procedure_started', 'Введена процедура'), ('procedure_ended', 'Окончена процедура'), ('dialog_started', 'Начат диалог'), ('dialog_ended', 'Окончен диалог'), ('file_received', 'Получен файл'), ('file_sent', 'Отправлен файл'), ('letter_outgoing', 'Направлено исходящее письмо'), ('letter_incoming', 'Получено входящее письмо'), ('reminder', 'Напоминание'), ('note_to_colleague', 'Сообщение коллеге'), ('call_outgoing', 'Исходящий звонок'), ('call_result', 'Результат звонка'), ('service_created', 'Услуга добавлена'), ('service_deleted', 'Услуга удалена'), ('consultation_booked', 'Записан на консультацию'), ('consultation_result', 'Результат консультации'), ('consultation_transferred', 'Консультация перенесена'), ('consultation_edited', 'Консультация изменена'), ('questionnaire_created', 'Анкета создана'), ('questionnaire_edited', 'Анкета отредактирована'), ('questionnaire_deleted', 'Анкета удалена'), ('schedule_created', 'Составлен график платежей'), ('schedule_updated', 'Изменён график платежей'), ('payment_in_created', 'Внесён входящий платёж'), ('payment_in_edited', 'Входящий платёж отредактирован'), ('payment_in_deleted', 'Входящий платёж удалён'), ('payment_out_created', 'Внесён исходящий платёж'), ('payment_out_edited', 'Исходящий платёж отредактирован'), ('payment_out_deleted', 'Исходящий платёж удалён'), ('charge_overdue', 'Начисление просрочено'), ('bubble_imported', 'Импортирован из Bubble'), ('bubble_enriched', 'Данные дополнены из Bubble'), ('lead_received', 'Получен лид с лендинга'), ('iskotpravlen', 'Иск отправлен в суд'), ('arbitr_event', 'Событие арбитражного дела'), ('system', 'Системное событие')], default='note', max_length=30, verbose_name='Тип события'),
        ),
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bubble_id', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Bubble ID')),
                ('direction', models.CharField(choices=[('outgoing', 'Исходящее'), ('incoming', 'Входящее')], default='outgoing', max_length=10, verbose_name='Направление')),
                ('subject_type', models.CharField(blank=True, help_text='Например, «Запрос в Росреестр», «Исковое заявление».', max_length=255, verbose_name='Тип письма')),
                ('outgoing_number', models.CharField(blank=True, max_length=100, verbose_name='Исходящий номер')),
                ('sent_at', models.DateField(blank=True, null=True, verbose_name='Дата отправки')),
                ('delivery_method', models.CharField(blank=True, choices=[('', '—'), ('post', 'Почта РФ'), ('email', 'Электронная почта'), ('site', 'Сайт организации'), ('telegram', 'Телеграмма'), ('courier', 'Нарочно / курьером')], default='', max_length=20, verbose_name='Способ отправки')),
                ('file_link', models.TextField(blank=True, help_text='URL Google Drive (исторический) или S3.', verbose_name='Ссылка на файл письма')),
                ('track_response', models.BooleanField(default=False, verbose_name='Отслеживать ответ')),
                ('control_date', models.DateField(blank=True, null=True, verbose_name='Контрольная дата')),
                ('response_received', models.BooleanField(default=False, verbose_name='Получен ответ')),
                ('response_date', models.DateField(blank=True, null=True, verbose_name='Дата ответа')),
                ('response_text', models.TextField(blank=True, verbose_name='Текст ответа')),
                ('response_number', models.CharField(blank=True, max_length=100, verbose_name='Номер ответа')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correspondences', to='crm.legalentity', verbose_name='Контрагент')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondences', to='crm.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Корреспонденция',
                'verbose_name_plural': 'Корреспонденция',
                'ordering': ['-sent_at', '-created_at'],
                'indexes': [models.Index(fields=['service', 'sent_at'], name='crm_corresp_service_f7b778_idx'), models.Index(fields=['direction'], name='crm_corresp_directi_641801_idx')],
            },
        ),
    ]
