# Generated by Django 5.2.10 on 2026-05-29 14:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_arbitr_menu_attach_to_configs'),
        ('crm', '0069_clientevent_bubble_id_alter_clientevent_event_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_system', models.BooleanField(default=False, help_text='Системные типы нельзя удалять из UI.', verbose_name='Системный')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тип действия',
                'verbose_name_plural': 'Типы действий',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('source', models.CharField(choices=[('system', 'Система'), ('court', 'Суд'), ('client', 'Клиент'), ('legal_entity', 'Юр. лицо'), ('employee', 'Сотрудник')], default='system', max_length=20, verbose_name='Источник')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_system', models.BooleanField(default=False, help_text='Системные типы нельзя удалять из UI.', verbose_name='Системный')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('standard_actions', models.ManyToManyField(blank=True, help_text='Действия, которые сотрудник должен выполнить при наступлении этого события. Используются как подсказки в UI.', related_name='standard_for_events', to='crm.actiontype', verbose_name='Стандартные действия')),
            ],
            options={
                'verbose_name': 'Тип события',
                'verbose_name_plural': 'Типы событий',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='actiontype',
            name='spawns_event',
            field=models.ForeignKey(blank=True, help_text='При записи действия автоматически создаётся событие этого типа.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spawned_by_actions', to='crm.eventtype', verbose_name='Порождает событие'),
        ),
        migrations.CreateModel(
            name='ClientLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bubble_id', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Bubble ID')),
                ('subject_kind', models.CharField(choices=[('client', 'Клиент'), ('company', 'Наша компания'), ('employee', 'Сотрудник')], default='client', max_length=10, verbose_name='Subject')),
                ('kind', models.CharField(choices=[('event', 'Событие'), ('action', 'Действие')], max_length=10, verbose_name='Тип записи')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('old_value', models.CharField(blank=True, max_length=255, verbose_name='Старое значение')),
                ('new_value', models.CharField(blank=True, max_length=255, verbose_name='Новое значение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('action_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='crm.actiontype', verbose_name='Тип действия')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='crm.client', verbose_name='Клиент')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to='core.employee', verbose_name='Сотрудник-актор')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='crm.clientlogentry', verbose_name='Родительская запись')),
                ('subject_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_as_subject', to='core.employee', verbose_name='Сотрудник (subject)')),
                ('event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='crm.eventtype', verbose_name='Тип события')),
            ],
            options={
                'verbose_name': 'Запись лога клиента',
                'verbose_name_plural': 'Лог клиента',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'created_at'], name='crm_clientl_client__3beccb_idx'), models.Index(fields=['subject_kind', 'kind'], name='crm_clientl_subject_e12666_idx'), models.Index(fields=['kind', 'event_type'], name='crm_clientl_kind_bcca97_idx'), models.Index(fields=['kind', 'action_type'], name='crm_clientl_kind_90c9ed_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('action_type__isnull', True), ('event_type__isnull', False), ('kind', 'event')), models.Q(('action_type__isnull', False), ('event_type__isnull', True), ('kind', 'action')), _connector='OR'), name='log_entry_kind_matches_type_fk')],
            },
        ),
    ]
