# Generated by Django 5.2.10 on 2026-05-29 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0071_seed_and_migrate_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientEvent',
        ),
    ]
