# Generated by Django 5.2.10 on 2026-05-31 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0072_drop_clientevent'),
        ('files', '0004_storedfile_bubble_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientlogentry',
            name='stored_file',
            field=models.ForeignKey(blank=True, help_text='Привязанный файл (для событий «Получен/Отправлен файл»)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to='files.storedfile', verbose_name='Файл'),
        ),
    ]
