# Generated by Django 5.2.10 on 2026-05-31 16:54

import django.db.models.deletion
from django.db import migrations, models


_INBOX_ALIASES = {"не принято", "непринятые"}


def seed_inbox(apps, schema_editor):
    """Всем активным сотрудникам — инбокс «Не принято». Существующие
    «Не принято»/«Непринятые» нормализуем (is_inbox=True, common_status=None),
    дубли сливаем (их states переносим на выбранный инбокс)."""
    Employee = apps.get_model("core", "Employee")
    SES = apps.get_model("crm", "ServiceEmployeeStatus")
    State = apps.get_model("crm", "ServiceEmployeeState")

    created = normalized = 0
    for emp in Employee.objects.filter(is_active=True):
        existing = list(SES.objects.filter(employee=emp))
        # кандидаты: уже inbox, иначе по имени
        cands = [s for s in existing if s.is_inbox] or [
            s for s in existing if (s.name or "").strip().lower() in _INBOX_ALIASES
        ]
        if cands:
            inbox = cands[0]
            inbox.name = "Не принято"
            inbox.is_inbox = True
            inbox.common_status = None
            inbox.order = 0
            inbox.is_active = True
            inbox.save()
            normalized += 1
            # слить остальные кандидаты в выбранный inbox
            for dup in cands[1:]:
                State.objects.filter(status=dup).update(status=inbox)
                dup.delete()
        else:
            SES.objects.create(
                employee=emp, name="Не принято", is_inbox=True,
                common_status=None, order=0, is_active=True,
            )
            created += 1
    print(f"  инбокс: создано {created}, нормализовано {normalized}")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_arbitr_menu_attach_to_configs'),
        ('crm', '0075_type_is_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceemployeestatus',
            name='is_inbox',
            field=models.BooleanField(default=False, help_text='Универсальная колонка для услуг, переданных сотруднику/отделу и ещё не принятых в работу. Одна на сотрудника, не привязана к стадии услуги (common_status пуст).', verbose_name='Инбокс «Не принято»'),
        ),
        migrations.AlterField(
            model_name='serviceemployeestatus',
            name='common_status',
            field=models.ForeignKey(blank=True, help_text='Пусто — универсальная колонка-инбокс «Не принято» (не привязана к стадии/услуге).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_statuses', to='crm.servicecommonstatus', verbose_name='Общий статус услуги'),
        ),
        migrations.RunPython(seed_inbox, noop),
        # AddConstraint вынесён в 0077 — нельзя создавать индекс в той же
        # транзакции, где RunPython уже сделал DML (pending trigger events).
    ]
