# Generated by Django 5.2.10 on 2026-06-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0078_actiontype_service_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='passport_division_code',
            field=models.CharField(blank=True, max_length=7, verbose_name='Код подразделения'),
        ),
    ]
