# Generated by Django 5.2.10 on 2026-06-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0079_client_passport_division_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='error_text',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Текст ошибки'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_failed',
            field=models.BooleanField(default=False, verbose_name='Ошибка доставки'),
        ),
    ]
