# Generated by Django 5.2.10 on 2026-06-11 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0081_eventtype_contract_fully_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='crm.messagetemplate', verbose_name='Шаблон'),
        ),
        migrations.AddField(
            model_name='message',
            name='template_params',
            field=models.JSONField(blank=True, default=list, help_text='Значения {{1}}, {{2}}… по порядку, переданные в sendTemplate.', verbose_name='Параметры шаблона'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='whatsapp_template_name',
            field=models.CharField(blank=True, default='', help_text='Латиница + подчёркивания (например, first_contact_intro). Используется в sendTemplate. Если пусто — генерируется из названия.', max_length=200, verbose_name='Имя шаблона в Meta'),
        ),
    ]
