# Generated by Django 5.2.10 on 2026-06-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0082_message_message_template_message_template_params_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontype',
            name='notifies',
            field=models.BooleanField(default=False, help_text='При записи действия этого типа сотрудникам, работающим с клиентом, приходит уведомление (на сайте + в Telegram-боте). Для действий, порождающих событие (spawns_event), ставьте флаг на стороне события.', verbose_name='Порождает уведомление'),
        ),
        migrations.AddField(
            model_name='actiontype',
            name='notify_hint',
            field=models.CharField(blank=True, help_text='Текст-подсказка в строке уведомления (что с этим делать).', max_length=255, verbose_name='Подсказка-что-делать'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='notifies',
            field=models.BooleanField(default=False, help_text='При записи события этого типа сотрудникам, работающим с клиентом, приходит уведомление (на сайте + в Telegram-боте).', verbose_name='Порождает уведомление'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='notify_hint',
            field=models.CharField(blank=True, help_text='Текст-подсказка в строке уведомления (что с этим делать).', max_length=255, verbose_name='Подсказка-что-делать'),
        ),
    ]
