# Generated by Django 5.2.10 on 2026-06-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0085_seed_notif_acknowledged_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='total_debt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Сумма всех долгов, ₽'),
        ),
    ]
