# Generated by Django 5.2.10 on 2026-06-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0086_service_total_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='docs_dept_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата передачи в отдел сбора документов'),
        ),
    ]
