# Generated by Django 5.2.10 on 2026-06-21 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0088_seed_sro_consent_types'),
        ('files', '0004_storedfile_bubble_id'),
        ('procedure', '0014_request_bubble_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondence',
            name='request',
            field=models.ForeignKey(blank=True, help_text='Для писем созданных в рамках запроса/ответа.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondences', to='procedure.request', verbose_name='Связанный запрос'),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='stored_file',
            field=models.ForeignKey(blank=True, help_text='FK на файл в S3 — заменяет file_link для новых записей.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondences', to='files.storedfile', verbose_name='Файл (StoredFile)'),
        ),
    ]
