# Generated by Django 5.2.10 on 2026-06-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0089_correspondence_request_correspondence_stored_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='fssp_code',
            field=models.CharField(blank=True, help_text='Код территориального органа ФССП из opendata.fssp.gov.ru (для идемпотентного импорта реестра ОСП).', max_length=20, null=True, unique=True, verbose_name='Код ОСП (ФССП)'),
        ),
    ]
