# Generated by Django 5.2.10 on 2026-06-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0092_court_code_and_kinds'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='arbitr_code',
            field=models.CharField(blank=True, default='', help_text='Префикс номера дела на kad — например «А12», «А40», «А56»', max_length=8, verbose_name='Код арбитражного суда (kad.arbitr.ru)'),
        ),
    ]
