# Generated by Django 5.2.10 on 2026-07-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0095_seed_claim_sent_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='ifns_code',
            field=models.CharField(blank=True, db_index=True, help_text='4-значный код инспекции ФНС (из open data nalog.ru). Для автоподбора инспекции по адресу клиента (Address.tax_office). Не unique — у УФНС и МИФНС коды могут повторяться/отсутствовать.', max_length=4, null=True, verbose_name='Код ИФНС'),
        ),
    ]
