# Generated by Django 5.2.10 on 2026-07-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0097_backfill_ifns_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Индекс для конвертов Почты РФ. Заполняется из адреса или через DaData, если в адресе индекса нет (напр. у МРЭО).', max_length=6, verbose_name='Почтовый индекс'),
        ),
    ]
