# Generated by Django 5.2.10 on 2026-08-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0101_region_arbitr_code_fill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondence',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
    ]
