# Generated by Django 5.2.10 on 2026-05-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BubbleFetchState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(choices=[('Man', 'Клиенты (Man)'), ('ProjectBFL', 'Услуги БФЛ (ProjectBFL)'), ('Money', 'Платежи и начисления (Money)'), ('MessageWSP', 'Сообщения WhatsApp (MessageWSP)'), ('Files', 'Файлы (Files)')], max_length=32, unique=True, verbose_name='Сущность')),
                ('cursor', models.PositiveIntegerField(default=0, verbose_name='Текущий курсор')),
                ('total_remote', models.PositiveIntegerField(default=0, verbose_name='Всего в Bubble')),
                ('total_fetched', models.PositiveIntegerField(default=0, verbose_name='Выкачано в staging')),
                ('last_fetch_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя выгрузка')),
            ],
            options={
                'verbose_name': 'Состояние выгрузки Bubble',
                'verbose_name_plural': 'Состояния выгрузки Bubble',
            },
        ),
        migrations.CreateModel(
            name='BubbleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(choices=[('Man', 'Клиенты (Man)'), ('ProjectBFL', 'Услуги БФЛ (ProjectBFL)'), ('Money', 'Платежи и начисления (Money)'), ('MessageWSP', 'Сообщения WhatsApp (MessageWSP)'), ('Files', 'Файлы (Files)')], db_index=True, max_length=32, verbose_name='Сущность')),
                ('bubble_id', models.CharField(db_index=True, max_length=64, verbose_name='Bubble _id')),
                ('raw', models.JSONField(default=dict, verbose_name='Сырой объект Bubble')),
                ('overrides', models.JSONField(blank=True, default=dict, verbose_name='Правки оператора')),
                ('display_title', models.CharField(blank=True, default='', max_length=300, verbose_name='Заголовок')),
                ('display_subtitle', models.CharField(blank=True, default='', max_length=300, verbose_name='Подзаголовок')),
                ('bubble_created', models.DateTimeField(blank=True, null=True, verbose_name='Создан в Bubble')),
                ('approved', models.BooleanField(default=False, verbose_name='Одобрен к импорту')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('imported', 'Импортирован'), ('skipped', 'Пропущен'), ('error', 'Ошибка')], db_index=True, default='pending', max_length=16, verbose_name='Статус импорта')),
                ('target_type', models.CharField(blank=True, default='', max_length=32, verbose_name='Модель-цель')),
                ('target_id', models.CharField(blank=True, default='', max_length=64, verbose_name='ID созданного объекта')),
                ('error', models.TextField(blank=True, default='', verbose_name='Текст ошибки')),
                ('fetched_at', models.DateTimeField(auto_now=True, verbose_name='Выгружен')),
                ('imported_at', models.DateTimeField(blank=True, null=True, verbose_name='Импортирован')),
            ],
            options={
                'verbose_name': 'Запись импорта Bubble',
                'verbose_name_plural': 'Записи импорта Bubble',
                'ordering': ['entity', 'bubble_created'],
                'indexes': [models.Index(fields=['entity', 'status'], name='bubble_impo_entity_615bd6_idx'), models.Index(fields=['entity', 'approved'], name='bubble_impo_entity_cac2ce_idx')],
                'constraints': [models.UniqueConstraint(fields=('entity', 'bubble_id'), name='uniq_bubble_entity_id')],
            },
        ),
    ]
