# Generated by Django 5.2.10 on 2026-05-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubble_import', '0002_seed_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='bubblerecord',
            name='display_status',
            field=models.CharField(blank=True, default='', help_text='Напр. статус услуги (statusPrj) — для отображения в аудите.', max_length=120, verbose_name='Статус из Bubble'),
        ),
        migrations.AlterField(
            model_name='bubblefetchstate',
            name='entity',
            field=models.CharField(choices=[('User', 'Сотрудники (User)'), ('Man', 'Клиенты (Man)'), ('ProjectBFL', 'Услуги БФЛ (ProjectBFL)'), ('Money', 'Платежи и начисления (Money)'), ('MessageWSP', 'Сообщения WhatsApp (MessageWSP)'), ('Files', 'Файлы (Files)')], max_length=32, unique=True, verbose_name='Сущность'),
        ),
        migrations.AlterField(
            model_name='bubblerecord',
            name='entity',
            field=models.CharField(choices=[('User', 'Сотрудники (User)'), ('Man', 'Клиенты (Man)'), ('ProjectBFL', 'Услуги БФЛ (ProjectBFL)'), ('Money', 'Платежи и начисления (Money)'), ('MessageWSP', 'Сообщения WhatsApp (MessageWSP)'), ('Files', 'Файлы (Files)')], db_index=True, max_length=32, verbose_name='Сущность'),
        ),
    ]
