# Generated by Django 5.2.10 on 2026-05-24 08:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubble_import', '0003_bubblerecord_display_status_and_more'),
        ('core', '0013_employee_bubble_id_alter_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='BubbleImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity', models.CharField(choices=[('User', 'Сотрудники (User)'), ('Man', 'Клиенты (Man)'), ('ProjectBFL', 'Услуги БФЛ (ProjectBFL)'), ('Money', 'Платежи и начисления (Money)'), ('MessageWSP', 'Сообщения WhatsApp (MessageWSP)'), ('Files', 'Файлы (Files)')], max_length=32, verbose_name='Сущность')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('done', 'Завершено'), ('error', 'Ошибка'), ('cancelled', 'Отменено')], db_index=True, default='pending', max_length=12, verbose_name='Статус')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('current_action', models.CharField(blank=True, default='', max_length=200, verbose_name='Текущее действие')),
                ('fetched_total', models.PositiveIntegerField(default=0, verbose_name='Выгружено всего')),
                ('applied_count', models.PositiveIntegerField(default=0, verbose_name='Импортировано')),
                ('errors_count', models.PositiveIntegerField(default=0, verbose_name='Ошибки')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='Пропущено')),
                ('remote_total', models.PositiveIntegerField(default=0, verbose_name='Всего в Bubble')),
                ('log_text', models.TextField(blank=True, default='', verbose_name='Лог (последние строки)')),
                ('error_text', models.TextField(blank=True, default='', verbose_name='Trace при ошибке')),
                ('cancel_requested', models.BooleanField(default=False)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=64)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bubble_import_jobs', to='core.employee')),
            ],
            options={
                'verbose_name': 'Задача импорта Bubble',
                'verbose_name_plural': 'Задачи импорта Bubble',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['entity', 'status'], name='bubble_impo_entity_539b2c_idx')],
            },
        ),
    ]
