# Generated by Django 5.2.10 on 2026-05-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubble_import', '0004_bubbleimportjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bubblefetchstate',
            name='entity',
            field=models.CharField(choices=[('User', 'Сотрудники (User)'), ('Man', 'Клиенты (Man)'), ('ProjectBFL', 'Услуги БФЛ (ProjectBFL)'), ('Money', 'Платежи и начисления (Money)'), ('MessageWSP', 'Сообщения WhatsApp (MessageWSP)'), ('Files', 'Файлы (Files)'), ('Organization', 'Юрлица (Organization → LegalEntity)'), ('Kreditors', 'Кредиторы клиента (Kreditors → Kreditor)')], max_length=32, unique=True, verbose_name='Сущность'),
        ),
        migrations.AlterField(
            model_name='bubbleimportjob',
            name='entity',
            field=models.CharField(choices=[('User', 'Сотрудники (User)'), ('Man', 'Клиенты (Man)'), ('ProjectBFL', 'Услуги БФЛ (ProjectBFL)'), ('Money', 'Платежи и начисления (Money)'), ('MessageWSP', 'Сообщения WhatsApp (MessageWSP)'), ('Files', 'Файлы (Files)'), ('Organization', 'Юрлица (Organization → LegalEntity)'), ('Kreditors', 'Кредиторы клиента (Kreditors → Kreditor)')], max_length=32, verbose_name='Сущность'),
        ),
        migrations.AlterField(
            model_name='bubblerecord',
            name='entity',
            field=models.CharField(choices=[('User', 'Сотрудники (User)'), ('Man', 'Клиенты (Man)'), ('ProjectBFL', 'Услуги БФЛ (ProjectBFL)'), ('Money', 'Платежи и начисления (Money)'), ('MessageWSP', 'Сообщения WhatsApp (MessageWSP)'), ('Files', 'Файлы (Files)'), ('Organization', 'Юрлица (Organization → LegalEntity)'), ('Kreditors', 'Кредиторы клиента (Kreditors → Kreditor)')], db_index=True, max_length=32, verbose_name='Сущность'),
        ),
    ]
