# Generated by Django 5.2.10 on 2026-06-02 13:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0018_department_can_edit_payment_schedule'),
        ('crm', '0078_actiontype_service_transfer'),
        ('files', '0004_storedfile_bubble_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutorOrg',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название (для выбора)')),
                ('intro_text', models.TextField(blank=True, help_text='Например: ООО «Сириус», ИНН … в лице директора …, действующего на основании Устава', verbose_name='Вводная строка ({ispolnitel})')),
                ('requisites', models.TextField(blank=True, help_text='Полный блок реквизитов: ИНН, ОГРН, р/счёт, банк, БИК, адрес и т.д.', verbose_name='Реквизиты ({Реквизиты_исполнителя})')),
                ('signer_name', models.CharField(blank=True, help_text='Подставляется в строку подписи: ____/ФИО', max_length=255, verbose_name='ФИО подписанта ({Исполнитель})')),
                ('is_default', models.BooleanField(default=False, help_text='Используется, если у услуги исполнитель не выбран явно.', verbose_name='По умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Организация-исполнитель',
                'verbose_name_plural': 'Организации-исполнители',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('kind', models.CharField(choices=[('contract_bfl', 'Договор юруслуг (БФЛ)'), ('other', 'Прочее')], default='other', max_length=32, verbose_name='Тип документа')),
                ('description', models.TextField(blank=True, verbose_name='Описание / список плейсхолдеров')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stored_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='afd_templates', to='files.storedfile', verbose_name='Файл шаблона (.docx)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='afd_templates_updated', to='core.employee', verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблоны документов',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afd_documents', to='crm.client', verbose_name='Клиент')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='afd_documents_created', to='core.employee', verbose_name='Кто сформировал')),
                ('docx_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='afd_generated_docx', to='files.storedfile', verbose_name='Готовый .docx')),
                ('pdf_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='afd_generated_pdf', to='files.storedfile', verbose_name='Готовый .pdf')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='afd_documents', to='crm.service', verbose_name='Услуга')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated', to='afd.documenttemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Сформированный документ',
                'verbose_name_plural': 'Сформированные документы',
                'ordering': ['-created_at'],
            },
        ),
    ]
