# Generated by Django 5.2.10 on 2026-06-04 16:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afd', '0002_seed_afd'),
    ]

    operations = [
        migrations.CreateModel(
            name='IskTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Шаблон заявления (иск)',
                'verbose_name_plural': 'Шаблоны заявлений (иски)',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IskSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('key', models.CharField(blank=True, max_length=64, verbose_name='Ключ')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок раздела')),
                ('body', models.TextField(blank=True, help_text='Плейсхолдеры {…} подставляются из данных. Вычисляемые: {debts_list} {creditors_block} {sum_total} {sum_overdue} {overdue_pct} {petition_sro} {appendix_list}', verbose_name='Текст (с плейсхолдерами {…})')),
                ('block_type', models.CharField(choices=[('text', 'Текст'), ('court_header', 'Шапка (суд + должник)'), ('creditors_header', 'Блок кредиторов (реквизиты)'), ('debts_list', 'Перечень задолженностей'), ('petition', 'Просительная часть'), ('appendix_list', 'Перечень приложений')], default='text', max_length=32, verbose_name='Тип блока')),
                ('align', models.CharField(choices=[('left', 'Слева'), ('center', 'По центру'), ('both', 'По ширине'), ('right', 'Справа')], default='both', max_length=8, verbose_name='Выравнивание')),
                ('bold', models.BooleanField(default=False, verbose_name='Жирный')),
                ('is_optional', models.BooleanField(default=False, verbose_name='Опциональный')),
                ('include_condition', models.CharField(blank=True, help_text='Если задан — раздел включается только когда флаг истинный (напр. has_property, has_income, is_married, has_sold_assets).', max_length=64, verbose_name='Условие включения (ключ флага)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='afd.isktemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Раздел заявления',
                'verbose_name_plural': 'Разделы заявления',
                'ordering': ['template', 'order'],
            },
        ),
    ]
