# Generated by Django 5.2.10 on 2026-06-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afd', '0005_isk_passport_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='kind',
            field=models.CharField(choices=[('contract_bfl', 'Договор юруслуг (БФЛ)'), ('request', 'Запрос в госорган'), ('other', 'Прочее')], default='other', max_length=32, verbose_name='Тип документа'),
        ),
    ]
