# Generated by Django 5.2.10 on 2026-06-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afd', '0006_alter_documenttemplate_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='kind',
            field=models.CharField(choices=[('contract_bfl', 'Договор юруслуг (БФЛ)'), ('request', 'Запрос в госорган'), ('efrsb', 'Сообщение ЕФРСБ'), ('other', 'Прочее')], default='other', max_length=32, verbose_name='Тип документа'),
        ),
    ]
