# Generated by Django 5.2.10 on 2026-05-04 12:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_seed_menu_legal_entities'),
        ('crm', '0048_clientevent_service_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnairePage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок страницы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Страница анкеты',
                'verbose_name_plural': 'Страницы анкеты',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('hint', models.CharField(blank=True, max_length=500, verbose_name='Подсказка')),
                ('question_type', models.CharField(choices=[('text', 'Короткий текст'), ('textarea', 'Большой текст'), ('choice', 'Один вариант'), ('multi_choice', 'Несколько вариантов'), ('yes_no', 'Да / Нет / Не знаю'), ('number', 'Число'), ('money', 'Сумма (руб.)'), ('date', 'Дата'), ('full_name_date', 'ФИО + дата рождения'), ('region_ref', 'Регион (справочник)'), ('legal_entity_ref', 'Юрлицо (справочник)'), ('client_ref', 'Клиент (справочник)'), ('employee_ref', 'Сотрудник (справочник)'), ('repeatable_group', 'Повторяемая группа')], default='text', max_length=30, verbose_name='Тип')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательный')),
                ('allow_custom_text', models.BooleanField(default=False, verbose_name='Разрешить свой текст')),
                ('show_if_value', models.CharField(blank=True, max_length=200, verbose_name='имеет значение')),
                ('legal_entity_kind', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.legalentitykind', verbose_name='Тип юрлица (фильтр)')),
                ('parent_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_questions', to='questionnaire.question', verbose_name='Родительская группа')),
                ('show_if_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_questions', to='questionnaire.question', verbose_name='Показывать если вопрос')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questionnaire.questionnairepage', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=300, verbose_name='Вариант ответа')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('has_extra_field', models.BooleanField(default=False, verbose_name='Доп. поле')),
                ('extra_field_hint', models.CharField(blank=True, max_length=200, verbose_name='Подсказка доп. поля')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='questionnaire.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответа',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Название анкеты')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_template', to='crm.servicename', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Шаблон анкеты',
                'verbose_name_plural': 'Шаблоны анкет',
                'ordering': ['service_name__short_name'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_page', models.PositiveIntegerField(default=0, verbose_name='Текущая страница')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Завершена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee', verbose_name='Заполнил')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_responses', to='crm.service', verbose_name='Услуга')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='questionnaire.questionnairetemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Ответ на анкету',
                'verbose_name_plural': 'Ответы на анкеты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='questionnairepage',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='questionnaire.questionnairetemplate', verbose_name='Шаблон'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_index', models.PositiveIntegerField(default=0, verbose_name='Индекс группы')),
                ('value', models.JSONField(default=dict, verbose_name='Значение')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questionnaire.question', verbose_name='Вопрос')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questionnaire.questionnaireresponse', verbose_name='Ответ на анкету')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопросы',
                'unique_together': {('response', 'question', 'group_index')},
            },
        ),
    ]
