# Generated by Django 5.2.10 on 2026-05-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionchoice',
            name='extra_field_type',
            field=models.CharField(choices=[('text', 'Текст'), ('client_ref', 'Выбор клиента'), ('employee_ref', 'Выбор сотрудника'), ('agent_ref', 'Выбор агента')], default='text', max_length=20, verbose_name='Тип доп. поля'),
        ),
    ]
