# Generated by Django 5.2.10 on 2026-05-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_choice_extra_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='default_value',
            field=models.CharField(blank=True, max_length=200, verbose_name='Значение по умолчанию'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Короткий текст'), ('textarea', 'Большой текст'), ('choice', 'Один вариант'), ('multi_choice', 'Несколько вариантов'), ('yes_no', 'Да / Нет / Не знаю'), ('number', 'Число'), ('money', 'Сумма (руб.)'), ('date', 'Дата'), ('full_name_date', 'ФИО + дата рождения'), ('region_ref', 'Регион (справочник)'), ('legal_entity_ref', 'Юрлицо (справочник)'), ('client_ref', 'Клиент (справочник)'), ('employee_ref', 'Сотрудник (справочник)'), ('repeatable_group', 'Повторяемая группа'), ('marital_status', 'Семейное положение'), ('bank_debts', 'Долги перед банками'), ('mfo_debts', 'Долги перед МФО'), ('property_assets', 'Имущество в собственности'), ('utility_debts', 'Коммунальные платежи'), ('fine_debts', 'Штрафы'), ('court_debts', 'Задолженности по решению суда'), ('other_debts', 'Иные задолженности'), ('sold_assets', 'Проданное имущество'), ('tax_debts', 'Неуплаченные налоги')], default='text', max_length=30, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='questionchoice',
            name='extra_field_type',
            field=models.CharField(choices=[('text', 'Текст'), ('name_amount', 'Наименование + Сумма (руб.)'), ('client_ref', 'Выбор клиента'), ('employee_ref', 'Выбор сотрудника'), ('agent_ref', 'Выбор агента')], default='text', max_length=20, verbose_name='Тип доп. поля'),
        ),
    ]
