# Generated by Django 5.2.10 on 2026-05-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_question_default_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='pdf_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='PDF сгенерирован'),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='pdf_s3_key',
            field=models.CharField(blank=True, max_length=500, verbose_name='PDF в S3'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Короткий текст'), ('textarea', 'Большой текст'), ('choice', 'Один вариант'), ('multi_choice', 'Несколько вариантов'), ('yes_no', 'Да / Нет / Не знаю'), ('number', 'Число'), ('money', 'Сумма (руб.)'), ('date', 'Дата'), ('full_name_date', 'ФИО + дата рождения'), ('region_ref', 'Регион (справочник)'), ('legal_entity_ref', 'Юрлицо (справочник)'), ('client_ref', 'Клиент (справочник)'), ('employee_ref', 'Сотрудник (справочник)'), ('repeatable_group', 'Повторяемая группа'), ('marital_status', 'Семейное положение'), ('bank_debts', 'Долги перед банками'), ('mfo_debts', 'Долги перед МФО'), ('property_assets', 'Имущество в собственности'), ('utility_debts', 'Коммунальные платежи'), ('fine_debts', 'Штрафы'), ('court_debts', 'Задолженности по решению суда'), ('other_debts', 'Иные задолженности'), ('sold_assets', 'Проданное имущество'), ('tax_debts', 'Неуплаченные налоги'), ('children_list', 'Дети (список)')], default='text', max_length=30, verbose_name='Тип'),
        ),
    ]
