# Generated by Django 5.2.10 on 2026-06-08 19:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0019_employee_can_handle_scans'),
        ('crm', '0080_message_error_text_message_is_failed'),
        ('files', '0004_storedfile_bubble_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('size', models.BigIntegerField(default=0, verbose_name='Размер (байт)')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='Тип')),
                ('source', models.CharField(choices=[('agent', 'Сканер (агент)'), ('manual', 'Загрузка вручную')], default='agent', max_length=20, verbose_name='Источник')),
                ('source_meta', models.CharField(blank=True, help_text='Например, имя устройства/папки сканера.', max_length=255, verbose_name='Метка источника')),
                ('status', models.CharField(choices=[('pending', 'Не привязан'), ('assigned', 'Привязан'), ('discarded', 'Отклонён')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Получен')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработан')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_scans', to='crm.client', verbose_name='Клиент')),
                ('client_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='files.clientfile', verbose_name='Файл клиента')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee', verbose_name='Обработал')),
                ('stored_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_scans', to='files.storedfile', verbose_name='Файл в хранилище')),
            ],
            options={
                'verbose_name': 'Входящий скан',
                'verbose_name_plural': 'Входящие сканы',
                'ordering': ['-received_at'],
            },
        ),
    ]
