# Generated by Django 5.2.10 on 2026-06-30 16:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0026_fix_daily_report_queue'),
        ('finance', '0004_incometype_is_legal_services'),
        ('reports', '0001_seed_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesBudget',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField(help_text='Первое число месяца (период отчёта).', unique=True, verbose_name='Месяц')),
                ('budget_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Бюджет отдела продаж')),
                ('calculated_at', models.DateTimeField(blank=True, null=True, verbose_name='Рассчитано')),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.employee', verbose_name='Кто рассчитал')),
            ],
            options={
                'verbose_name': 'Бюджет отдела продаж',
                'verbose_name_plural': 'Бюджеты отдела продаж',
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='SalesBudgetEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('computed', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Расчётное начисление')),
                ('accrued', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Начислено в бюджет отдела продаж')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='reports.salesbudget', verbose_name='Бюджет (месяц)')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='finance.payment', verbose_name='Платёж (представитель операции)')),
            ],
            options={
                'verbose_name': 'Начисление в бюджет ОП',
                'verbose_name_plural': 'Начисления в бюджет ОП',
                'constraints': [models.UniqueConstraint(fields=('budget', 'payment'), name='uniq_salesbudget_entry')],
            },
        ),
    ]
