# Generated by Django 5.2.10 on 2026-06-14 12:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0023_employee_telegram_chat_id'),
        ('crm', '0085_seed_notif_acknowledged_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureStage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('kind_scope', models.CharField(choices=[('common', 'Общая (стадии дела)'), ('restructuring', 'Реструктуризация долгов'), ('realization', 'Реализация имущества')], default='common', max_length=20, verbose_name='Область')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_terminal', models.BooleanField(default=False, help_text='Стадия «Завершено».', verbose_name='Завершающая')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Стадия процедуры',
                'verbose_name_plural': 'Стадии процедур',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BankruptcyCase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'В работе'), ('closed', 'Дело закрыто')], default='active', max_length=12, verbose_name='Статус дела')),
                ('fm_name_external', models.CharField(blank=True, help_text='ФИО АУ, если он не штатный сотрудник.', max_length=255, verbose_name='Финуправляющий (внешний)')),
                ('filing_date', models.DateField(blank=True, null=True, verbose_name='Дата подачи заявления в суд')),
                ('accept_date', models.DateField(blank=True, null=True, verbose_name='Дата первого заседания / принятия')),
                ('first_hearing_outcome', models.CharField(blank=True, choices=[('fh_refused', 'Отказано во введении процедуры'), ('fh_intro_restructuring', 'Введена процедура реструктуризации'), ('fh_intro_realization', 'Введена процедура реализации имущества'), ('fh_settlement', 'Мировое соглашение')], max_length=32, verbose_name='Итог первого заседания')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('financial_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_cases', to='core.employee', verbose_name='Финуправляющий (штатный)')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bankruptcy_case', to='crm.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Дело о банкротстве',
                'verbose_name_plural': 'Дела о банкротстве',
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('restructuring', 'Реструктуризация долгов'), ('realization', 'Реализация имущества')], max_length=20, verbose_name='Вид процедуры')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('intro_date', models.DateField(blank=True, null=True, verbose_name='Дата определения о введении')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Дата публикации (ЕФРСБ/Коммерсантъ)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала процедуры')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания процедуры')),
                ('outcome', models.CharField(blank=True, choices=[('restr_plan_approved', 'Утверждён план реструктуризации'), ('restr_intro_realization', 'Введена процедура реализации имущества'), ('restr_settlement', 'Заключено мировое соглашение'), ('restr_terminated', 'Прекращение процедуры'), ('real_discharge_full', 'Освобождение от обязательств (полное списание долгов)'), ('real_discharge_partial', 'Частичное освобождение от обязательств (списано часть долгов)'), ('real_no_discharge', 'Завершение процедуры без списания долгов'), ('real_settlement', 'Заключено мировое соглашение'), ('real_proceedings_terminated', 'Производство по делу прекращено')], max_length=40, verbose_name='Исход процедуры')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='procedure.bankruptcycase', verbose_name='Дело')),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_procedures', to='procedure.procedurestage', verbose_name='Текущая стадия')),
            ],
            options={
                'verbose_name': 'Процедура',
                'verbose_name_plural': 'Процедуры',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='bankruptcycase',
            name='current_procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_in_cases', to='procedure.procedure', verbose_name='Активная процедура'),
        ),
        migrations.CreateModel(
            name='MilestoneTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=60, unique=True, verbose_name='Код')),
                ('title', models.CharField(max_length=255, verbose_name='Мероприятие')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('base_date_key', models.CharField(blank=True, choices=[('case_filing_date', 'Дата подачи заявления в суд'), ('case_accept_date', 'Дата первого заседания / принятия'), ('proc_intro_date', 'Дата определения о введении процедуры'), ('proc_publication_date', 'Дата публикации (ЕФРСБ/Коммерсантъ)'), ('proc_start_date', 'Дата начала процедуры')], help_text='От какой даты считать дедлайн. Пусто — без срока.', max_length=32, verbose_name='Базовая дата (якорь срока)')),
                ('offset_days', models.IntegerField(default=0, help_text='Дедлайн = базовая дата + N дней (можно отрицательное).', verbose_name='Смещение, дней')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Обязательное')),
                ('responsible_role', models.CharField(blank=True, max_length=20, verbose_name='Ответственная роль')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_draft', models.BooleanField(default=True, help_text='Состав/сроки подлежат подтверждению АУ. Бейдж в UI.', verbose_name='Черновик (срок не подтверждён)')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milestone_templates', to='procedure.procedurestage', verbose_name='Стадия')),
            ],
            options={
                'verbose_name': 'Шаблон мероприятия',
                'verbose_name_plural': 'Шаблоны мероприятий',
                'ordering': ['stage__order', 'order'],
            },
        ),
        migrations.AddField(
            model_name='bankruptcycase',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_cases', to='procedure.procedurestage', verbose_name='Текущая стадия'),
        ),
        migrations.CreateModel(
            name='ProcedureMilestone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Мероприятие')),
                ('base_date_key', models.CharField(blank=True, max_length=32, verbose_name='Базовая дата (якорь)')),
                ('offset_days', models.IntegerField(default=0, verbose_name='Смещение, дней')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Обязательное')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('done', 'Выполнено'), ('overdue', 'Просрочено'), ('na', 'Не применимо'), ('skipped', 'Пропущено')], default='pending', max_length=12, verbose_name='Статус')),
                ('is_manual', models.BooleanField(default=False, verbose_name='Добавлено вручную')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='Выполнено в')),
                ('artifact_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('artifact_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='procedure.bankruptcycase', verbose_name='Дело')),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_milestones', to='core.employee', verbose_name='Кто выполнил')),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='procedure.procedure', verbose_name='Процедура')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedure_milestones', to='core.employee', verbose_name='Ответственный')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='procedure.milestonetemplate', verbose_name='Шаблон')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestones', to='procedure.procedurestage', verbose_name='Стадия')),
            ],
            options={
                'verbose_name': 'Мероприятие процедуры',
                'verbose_name_plural': 'Мероприятия процедур',
                'ordering': ['procedure__order', 'stage__order', 'due_date', 'title'],
                'indexes': [models.Index(fields=['case', 'status'], name='procedure_p_case_id_2a684d_idx'), models.Index(fields=['due_date'], name='procedure_p_due_dat_4dffd0_idx'), models.Index(fields=['status', 'due_date'], name='procedure_p_status_952452_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('procedure__isnull', False), ('template__isnull', False)), fields=('procedure', 'template'), name='uniq_milestone_per_proc_template'), models.UniqueConstraint(condition=models.Q(('procedure__isnull', True), ('template__isnull', False)), fields=('case', 'template'), name='uniq_milestone_per_case_template')],
            },
        ),
    ]
