# Generated by Django 5.2.10 on 2026-06-14 13:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0085_seed_notif_acknowledged_action'),
        ('procedure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной должник')),
                ('full_name', models.CharField(blank=True, max_length=300, verbose_name='ФИО')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('passport', models.TextField(blank=True, verbose_name='Паспортные данные')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('snils', models.CharField(blank=True, max_length=14, verbose_name='СНИЛС')),
                ('reg_address', models.TextField(blank=True, verbose_name='Адрес регистрации')),
                ('actual_address', models.TextField(blank=True, verbose_name='Адрес фактический')),
                ('phones', models.CharField(blank=True, max_length=255, verbose_name='Телефоны')),
                ('total_debt', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Сумма всех долгов')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debtors', to='procedure.bankruptcycase', verbose_name='Дело')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debtor_records', to='crm.client', verbose_name='Карточка клиента')),
            ],
            options={
                'verbose_name': 'Должник',
                'verbose_name_plural': 'Должники',
                'ordering': ['order'],
            },
        ),
    ]
