# Generated by Django 5.2.10 on 2026-06-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0002_debtor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankruptcycase',
            name='accept_date',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='passport',
        ),
        migrations.AddField(
            model_name='bankruptcycase',
            name='claim_accept_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приёма иска в суде'),
        ),
        migrations.AddField(
            model_name='bankruptcycase',
            name='first_hearing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата первого судебного заседания'),
        ),
        migrations.AddField(
            model_name='bankruptcycase',
            name='next_hearing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата следующего судебного заседания'),
        ),
        migrations.AddField(
            model_name='debtor',
            name='birth_place',
            field=models.CharField(blank=True, max_length=500, verbose_name='Место рождения'),
        ),
        migrations.AddField(
            model_name='debtor',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='debtor',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='debtor',
            name='passport_division_code',
            field=models.CharField(blank=True, max_length=7, verbose_name='Код подразделения'),
        ),
        migrations.AddField(
            model_name='debtor',
            name='passport_issued_by',
            field=models.CharField(blank=True, max_length=500, verbose_name='Кем выдан'),
        ),
        migrations.AddField(
            model_name='debtor',
            name='passport_issued_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AddField(
            model_name='debtor',
            name='passport_number',
            field=models.CharField(blank=True, max_length=6, verbose_name='Номер паспорта'),
        ),
        migrations.AddField(
            model_name='debtor',
            name='passport_series',
            field=models.CharField(blank=True, max_length=4, verbose_name='Серия паспорта'),
        ),
        migrations.AddField(
            model_name='debtor',
            name='patronymic',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='term_months',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Обычно от 4 до 6 месяцев.', null=True, verbose_name='Срок процедуры, мес.'),
        ),
        migrations.AlterField(
            model_name='bankruptcycase',
            name='filing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата подачи иска в суд'),
        ),
        migrations.AlterField(
            model_name='milestonetemplate',
            name='base_date_key',
            field=models.CharField(blank=True, choices=[('case_filing_date', 'Дата подачи иска в суд'), ('case_claim_accept_date', 'Дата приёма иска в суде'), ('case_first_hearing_date', 'Дата первого судебного заседания'), ('proc_intro_date', 'Дата решения о введении процедуры'), ('proc_publication_date', 'Дата публикации (ЕФРСБ/Коммерсантъ)'), ('proc_start_date', 'Дата начала процедуры')], help_text='От какой даты считать дедлайн. Пусто — без срока.', max_length=32, verbose_name='Базовая дата (якорь срока)'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='intro_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата решения о введении процедуры'),
        ),
    ]
