# Generated by Django 5.2.10 on 2026-06-14 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0003_remove_bankruptcycase_accept_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Debtor',
        ),
    ]
