# Generated by Django 5.2.10 on 2026-06-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0004_delete_debtor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankruptcycase',
            name='next_hearing_date',
        ),
        migrations.AddField(
            model_name='procedure',
            name='next_hearing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата следующего судебного заседания'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата решения об окончании/завершении процедуры'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='intro_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата принятия решения о введении процедуры'),
        ),
    ]
