# Generated by Django 5.2.10 on 2026-06-14 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_department_is_docs_collection'),
        ('procedure', '0005_remove_bankruptcycase_next_hearing_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankruptcycase',
            name='financial_manager',
        ),
        migrations.RemoveField(
            model_name='bankruptcycase',
            name='fm_name_external',
        ),
        migrations.AddField(
            model_name='procedure',
            name='financial_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_procedures', to='core.employee', verbose_name='Финуправляющий (штатный)'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='fm_name_external',
            field=models.CharField(blank=True, help_text='ФИО АУ, если он не штатный сотрудник.', max_length=255, verbose_name='Финуправляющий (внешний)'),
        ),
    ]
