# Generated by Django 5.2.10 on 2026-06-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0006_remove_bankruptcycase_financial_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='start_date',
        ),
        migrations.AddField(
            model_name='procedure',
            name='publication_efrsb_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата публикации в ЕФРСБ'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='publication_kommersant_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата публикации в КоммерсантЪ'),
        ),
        migrations.AlterField(
            model_name='milestonetemplate',
            name='base_date_key',
            field=models.CharField(blank=True, choices=[('case_filing_date', 'Дата подачи иска в суд'), ('case_claim_accept_date', 'Дата приёма иска в суде'), ('case_first_hearing_date', 'Дата первого судебного заседания'), ('proc_intro_date', 'Дата решения о введении процедуры'), ('proc_publication_efrsb_date', 'Дата публикации в ЕФРСБ'), ('proc_publication_kommersant_date', 'Дата публикации в КоммерсантЪ')], help_text='От какой даты считать дедлайн. Пусто — без срока.', max_length=32, verbose_name='Базовая дата (якорь срока)'),
        ),
    ]
