# Generated by Django 5.2.10 on 2026-06-21 11:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_department_is_docs_collection'),
        ('crm', '0088_seed_sro_consent_types'),
        ('procedure', '0008_seed_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=60, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Тип запроса')),
                ('response_days', models.PositiveSmallIntegerField(default=30, help_text='Через сколько дней ждём ответ (для контроля срока).', verbose_name='Срок ответа, дней')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_draft', models.BooleanField(default=True, help_text='Состав/сроки подлежат подтверждению юристом. Бейдж в UI.', verbose_name='Черновик (не подтверждён)')),
                ('default_recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.legalentity', verbose_name='Госорган по умолчанию')),
            ],
            options={
                'verbose_name': 'Тип запроса',
                'verbose_name_plural': 'Типы запросов',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RequestPackage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=60, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Пакет запросов')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_draft', models.BooleanField(default=True, verbose_name='Черновик (не подтверждён)')),
                ('types', models.ManyToManyField(blank=True, related_name='packages', to='procedure.requesttype', verbose_name='Типы запросов')),
            ],
            options={
                'verbose_name': 'Пакет запросов',
                'verbose_name_plural': 'Пакеты запросов',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('recipient_name', models.CharField(blank=True, max_length=255, verbose_name='Госорган (текст)')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('answered', 'Ответ получен'), ('no_answer', 'Без ответа')], default='draft', max_length=12, verbose_name='Статус')),
                ('sent_method', models.CharField(blank=True, choices=[('email', 'Email'), ('post', 'Почта России'), ('courier', 'Курьер'), ('site', 'Сайт / портал'), ('handed', 'Нарочно'), ('other', 'Иное')], max_length=12, verbose_name='Способ отправки')),
                ('sent_date', models.DateField(blank=True, null=True, verbose_name='Дата отправки')),
                ('response_days', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Срок ответа, дней')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок ответа (до)')),
                ('overdue_notified', models.BooleanField(default=False, verbose_name='Уведомление о просрочке отправлено')),
                ('response_date', models.DateField(blank=True, null=True, verbose_name='Дата ответа')),
                ('response_number', models.CharField(blank=True, max_length=120, verbose_name='Номер ответа')),
                ('response_text', models.TextField(blank=True, verbose_name='Текст/итог ответа')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='procedure.bankruptcycase', verbose_name='Дело')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.employee', verbose_name='Кто создал')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.legalentity', verbose_name='Госорган')),
                ('request_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='procedure.requesttype', verbose_name='Тип запроса')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['case', 'status'], name='procedure_r_case_id_9b80d8_idx'), models.Index(fields=['due_date'], name='procedure_r_due_dat_5d0b62_idx')],
            },
        ),
    ]
