# Generated by Django 5.2.10 on 2026-06-21 12:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_department_is_docs_collection'),
        ('crm', '0088_seed_sro_consent_types'),
        ('files', '0004_storedfile_bubble_id'),
        ('procedure', '0009_requesttype_requestpackage_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='financial_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_procedures', to='core.employee', verbose_name='Финуправляющий (штатный, legacy)'),
        ),
        migrations.CreateModel(
            name='ArbitrationManager',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=120, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=120, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=120, verbose_name='Отчество')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='ИНН')),
                ('snils', models.CharField(blank=True, max_length=20, verbose_name='СНИЛС')),
                ('corr_address', models.CharField(blank=True, max_length=400, verbose_name='Адрес для корреспонденции')),
                ('phone', models.CharField(blank=True, max_length=120, verbose_name='Телефон / факс')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='E-mail')),
                ('sro_text', models.CharField(blank=True, help_text='Если СРО не выбран из реестра — текстом для подстановки.', max_length=500, verbose_name='Реквизиты СРО (текст)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arbitration_profiles', to='core.employee', verbose_name='Сотрудник (если штатный)')),
                ('signature_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='files.storedfile', verbose_name='Подпись (PNG)')),
                ('sro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.legalentity', verbose_name='СРО')),
                ('stamp_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='files.storedfile', verbose_name='Печать (PNG)')),
            ],
            options={
                'verbose_name': 'Арбитражный управляющий',
                'verbose_name_plural': 'Арбитражные управляющие',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='procedure',
            name='arbitr_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures', to='procedure.arbitrationmanager', verbose_name='Финуправляющий (АУ)'),
        ),
    ]
