# Generated by Django 5.2.10 on 2026-06-21 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afd', '0006_alter_documenttemplate_kind'),
        ('files', '0004_storedfile_bubble_id'),
        ('procedure', '0010_alter_procedure_financial_manager_arbitrationmanager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='document_docx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='files.storedfile', verbose_name='Документ (.docx)'),
        ),
        migrations.AddField(
            model_name='request',
            name='document_pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='files.storedfile', verbose_name='Документ (PDF)'),
        ),
        migrations.AddField(
            model_name='request',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Сформирован'),
        ),
        migrations.AddField(
            model_name='request',
            name='outgoing_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Исходящий №'),
        ),
        migrations.AddField(
            model_name='request',
            name='with_signature',
            field=models.BooleanField(default=False, verbose_name='С подписью и печатью'),
        ),
        migrations.AddField(
            model_name='requesttype',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='afd.documenttemplate', verbose_name='Шаблон документа (.docx)'),
        ),
    ]
