# Generated by Django 5.2.10 on 2026-06-21 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_storedfile_bubble_id'),
        ('procedure', '0011_request_document_docx_request_document_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='response_scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='files.storedfile', verbose_name='Скан ответа'),
        ),
    ]
