# Generated by Django 5.2.10 on 2026-06-21 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_storedfile_bubble_id'),
        ('procedure', '0012_request_response_scan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arbitrationmanager',
            name='stamp_file',
        ),
        migrations.AlterField(
            model_name='arbitrationmanager',
            name='signature_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='files.storedfile', verbose_name='Подпись и печать (PNG)'),
        ),
    ]
