# Generated by Django 5.2.10 on 2026-07-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0014_request_bubble_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankruptcycase',
            name='filing_method',
            field=models.CharField(blank=True, choices=[('post', 'Почта России'), ('court_office', 'Канцелярия суда'), ('kad', 'Сайт суда (kad.arbitr.ru)')], max_length=16, verbose_name='Способ отправки иска'),
        ),
    ]
