# Generated by Django 5.2.10 on 2026-07-06 15:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_fix_daily_report_queue'),
        ('crm', '0096_legalentity_ifns_code'),
        ('procedure', '0015_bankruptcycase_filing_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttype',
            name='recipient_kind',
            field=models.ForeignKey(blank=True, help_text='Какой вид ЮЛ подбирать в адресаты (МРЭО/ГИМС/ФНС/ЗАГС/суд…).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.legalentitykind', verbose_name='Вид госоргана (для подбора)'),
        ),
        migrations.AddField(
            model_name='requesttype',
            name='recipient_lookup',
            field=models.CharField(choices=[('none', 'Не требуется (СМЭВ)'), ('region', 'По виду и региону клиента'), ('fns_by_address', 'ФНС по адресу клиента'), ('manual', 'Только вручную')], default='manual', max_length=16, verbose_name='Способ определения адресата'),
        ),
        migrations.CreateModel(
            name='RecipientRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('district', models.CharField(blank=True, default='', max_length=255, verbose_name='Район/город (нормализованный)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.employee', verbose_name='Кто сохранил')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='crm.legalentitykind', verbose_name='Вид госоргана')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='crm.legalentity', verbose_name='Госорган')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='crm.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Правило адресата',
                'verbose_name_plural': 'Правила адресатов',
                'ordering': ['kind__short_name', 'region__number', 'district'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'region', 'district'), name='uniq_recipient_rule_kind_region_district')],
            },
        ),
    ]
