# Generated by Django 5.2.10 on 2026-07-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0017_seed_recipient_lookup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttype',
            name='recipient_lookup',
            field=models.CharField(choices=[('none', 'Не требуется (СМЭВ)'), ('region', 'По виду и региону клиента'), ('fns_by_address', 'ФНС по адресу клиента'), ('manual', 'Только вручную'), ('debtor', 'Должник (сам клиент)'), ('creditors', 'Кредиторы (письмо каждому)')], default='manual', max_length=16, verbose_name='Способ определения адресата'),
        ),
    ]
