# Generated by Django 5.2.10 on 2026-07-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0021_assetdocument_incomecertificate_landplot_otherasset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitrationmanager',
            name='ops_index',
            field=models.CharField(blank=True, help_text='Шестизначный индекс отделения, через которое АУ сдаёт почту (колонка INDEXFROM в выгрузке для Почты России).', max_length=6, verbose_name='Индекс ОПС отправки'),
        ),
        migrations.AddField(
            model_name='request',
            name='pages_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Считается при формировании/загрузке PDF. Нужен для веса письма в выгрузке для Почты России (пустой → вес по умолчанию).', null=True, verbose_name='Страниц в документе'),
        ),
    ]
