# Generated by Django 5.2.10 on 2026-08-21 10:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0036_employee_kommersant_email_and_more'),
        ('files', '0004_storedfile_bubble_id'),
        ('procedure', '0022_request_pages_count_and_ops_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(verbose_name='ID владельца')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype', verbose_name='Тип владельца')),
                ('stored_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='files.storedfile', verbose_name='Файл')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.employee', verbose_name='Кто загрузил')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='procedure_d_content_d43202_idx')],
            },
        ),
    ]
