# Generated by Django 5.2.10 on 2026-08-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0023_alter_request_notes_documentattachment'),
    ]

    def _backfill(apps, schema_editor):
        """У всех существующих запросов PDF собирался вместе с .docx.

        Без этого `pdf_is_stale` посчитал бы устаревшими ВСЕ 35 тыс. запросов
        и в таблице повсюду висел бы бейдж «PDF устарел».
        """
        Request = apps.get_model("procedure", "Request")
        (Request.objects
         .filter(document_pdf__isnull=False, pdf_built_at__isnull=True)
         .update(pdf_built_at=models.F("generated_at")))

    operations = [
        migrations.AddField(
            model_name='request',
            name='pdf_built_at',
            field=models.DateTimeField(blank=True, help_text='Когда PDF последний раз собирали из .docx. Отстаёт от «Сформирован», если документ правили в онлайн-редакторе, а PDF ещё не пересобирали.', null=True, verbose_name='PDF собран'),
        ),
        migrations.RunPython(_backfill, migrations.RunPython.noop),
    ]
