# Generated by Django 5.2.10 on 2026-08-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0024_request_pdf_built_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttype',
            name='region_office_prefix',
            field=models.CharField(blank=True, help_text='Заполнено → адресат берётся на уровне РЕГИОНА, а не района: среди органов вида ищется тот, чьё название начинается с этой строки (напр. «УГИБДД»). Пусто → обычный подбор, с сужением по району/городу клиента.', max_length=60, verbose_name='Областное управление: начало названия'),
        ),
    ]
