# Generated by Django 5.2.10 on 2026-08-29 18:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_employee_can_access_callcenter'),
        ('crm', '0102_alter_correspondence_comments'),
        ('procedure', '0026_alter_requesttype_recipient_lookup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(blank=True, help_text='Сквозной порядковый номер кредитора внутри дела.', null=True, verbose_name='Номер кредитора')),
                ('kind', models.CharField(choices=[('legal', 'Юридическое лицо'), ('person', 'Физическое лицо')], default='legal', max_length=10, verbose_name='Вид лица')),
                ('name', models.CharField(help_text='Для юрлица — наименование, для физлица — ФИО.', max_length=500, verbose_name='Наименование / ФИО')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('ogrn', models.CharField(blank=True, max_length=15, verbose_name='ОГРН / ОГРНИП')),
                ('corr_address', models.TextField(blank=True, verbose_name='Адрес для корреспонденции')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Банк')),
                ('bik', models.CharField(blank=True, max_length=9, verbose_name='БИК')),
                ('settlement_account', models.CharField(blank=True, max_length=20, verbose_name='Расчётный счёт')),
                ('correspondent_account', models.CharField(blank=True, max_length=20, verbose_name='Корр. счёт')),
                ('account_holder', models.CharField(blank=True, help_text='Если отличается от наименования кредитора.', max_length=255, verbose_name='Получатель платежа')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Сумма требований (общая)')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='Контактное лицо')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('source', models.CharField(choices=[('manual', 'Заведён вручную'), ('questionnaire', 'Импортирован из анкеты')], default='manual', max_length=16, verbose_name='Источник')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditors', to='procedure.bankruptcycase', verbose_name='Дело')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.employee', verbose_name='Кто завёл')),
                ('legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.legalentity', verbose_name='Кредитор в реестре юрлиц')),
            ],
            options={
                'verbose_name': 'Кредитор',
                'verbose_name_plural': 'Кредиторы',
                'ordering': ['number', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('queue', models.CharField(choices=[('first', 'Первая очередь'), ('second', 'Вторая очередь'), ('third_pledge', 'Третья очередь — залог'), ('third_main', 'Третья очередь — основной долг'), ('third_penalty', 'Третья очередь — пени/штрафы')], default='third_main', max_length=20, verbose_name='Очередность удовлетворения')),
                ('registry_date', models.DateField(blank=True, null=True, verbose_name='Дата внесения записи в РТК')),
                ('registry_number', models.CharField(blank=True, help_text='Номер записи так, как он проставлен в самом реестре.', max_length=50, verbose_name='Номер кредитора по реестру')),
                ('amendment_note', models.TextField(blank=True, verbose_name='Отметка о внесении изменений')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Сумма требования')),
                ('basis', models.CharField(blank=True, help_text='Определение суда, договор, судебный приказ и т. п.', max_length=500, verbose_name='Основание')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.employee', verbose_name='Кто завёл')),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='procedure.creditor', verbose_name='Кредитор')),
            ],
            options={
                'verbose_name': 'Требование кредитора',
                'verbose_name_plural': 'Требования кредиторов',
                'ordering': ['queue', 'registry_date', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='creditor',
            constraint=models.UniqueConstraint(fields=('case', 'number'), name='uniq_creditor_number_per_case'),
        ),
    ]
