# Generated by Django 5.2.10 on 2026-03-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfile',
            name='content_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='storedfile',
            name='size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
