# Generated by Django 5.2.10 on 2026-05-07 15:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_seed_menu_legal_entities'),
        ('crm', '0049_clientevent_questionnaire_types'),
        ('files', '0002_storedfile_content_type_storedfile_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.CharField(blank=True, max_length=50, verbose_name='Системный ключ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='crm.client', verbose_name='Клиент')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='files.clientfolder', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Папка клиента',
                'verbose_name_plural': 'Папки клиентов',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClientFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('size', models.BigIntegerField(default=0, verbose_name='Размер (байт)')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='Тип')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stored_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_files', to='files.storedfile')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee', verbose_name='Загрузил')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='files.clientfolder', verbose_name='Папка')),
            ],
            options={
                'verbose_name': 'Файл клиента',
                'verbose_name_plural': 'Файлы клиентов',
                'ordering': ['-created_at'],
            },
        ),
    ]
