# Generated by Django 5.2.10 on 2026-05-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_client_folders_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfile',
            name='bubble_id',
            field=models.CharField(blank=True, help_text='ID записи Files в исходной CRM на bubble.io', max_length=64, null=True, unique=True),
        ),
    ]
