# Generated by Django 5.2.10 on 2026-06-13 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0023_employee_telegram_chat_id'),
        ('crm', '0083_actiontype_notifies_actiontype_notify_hint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Снимок текста уведомления (переживает изменение source).', max_length=500, verbose_name='Текст')),
                ('hint', models.CharField(blank=True, max_length=255, verbose_name='Подсказка-что-делать')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('accepted', 'В работе'), ('done', 'Исполнено'), ('rejected', 'Отклонено'), ('snoozed', 'Отложено')], db_index=True, default='new', max_length=12, verbose_name='Статус')),
                ('snooze_until', models.DateTimeField(blank=True, null=True, verbose_name='Отложено до')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Время реакции')),
                ('responded_via', models.CharField(blank=True, choices=[('web', 'Сайт'), ('telegram', 'Telegram')], max_length=10, verbose_name='Канал реакции')),
                ('tg_message_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='crm.client', verbose_name='Клиент')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.employee', verbose_name='Получатель')),
                ('response_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.clientlogentry', verbose_name='Запись-ответ в событийке')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='crm.clientlogentry', verbose_name='Запись событийки')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'status'], name='notificatio_recipie_e285de_idx'), models.Index(fields=['status', 'snooze_until'], name='notificatio_status_0194f2_idx')],
            },
        ),
    ]
