# Generated by Django 5.2.10 on 2026-06-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('accepted', 'В работе'), ('done', 'Исполнено'), ('rejected', 'Отклонено'), ('snoozed', 'Отложено'), ('acknowledged', 'Ознакомлен')], db_index=True, default='new', max_length=12, verbose_name='Статус'),
        ),
    ]
